Integrate DBE Python tests into OmnisciDB unit testing
intel-ai/omniscidb pull request #115
Opened 2020-11-06 07:17 UTC by igalink

1. New cmake target added: dbe_tests. It builds just DBE libraries (libDBEngine.so, dbe.so) and run C++ and Python tests for DBE only. It also generates calcite jar.

2. DBE tests (C++ and Python) added to all_tests target.

3.  thrift_gen dependency added to QueryState library because it requires the gen-cpp files.

2020-11-06 10:13 UTC, ienkovich commented on Tests/CMakeLists.txt
> +  add_dependencies(dbe_tests dbe4py-test)
Shouldn't we also add `dbe_tests` to `all_tests` dependencies?

2020-11-06 12:58 UTC, igalink commented on Tests/CMakeLists.txt
> +  add_dependencies(dbe_tests dbe4py-test)
C++ DBE tests already in the DBE_TEST_PROGRAMS. So only Python tests should be added (dbe4py-test)

2020-11-06 13:07 UTC, anton-malakhov requested changes
LGTM though I have a few questions

2020-11-06 13:07 UTC, anton-malakhov commented on Embedded/CMakeLists.txt
> +        DEPENDS DBEngine ${pydeps} mapd_java_components
the first COMMAND can be removed if you replace DEPENDS by reference to dbe4py

2020-11-06 13:07 UTC, anton-malakhov commented on Tests/CMakeLists.txt
> +  add_dependencies(all_tests dbe4py-test)
do you mean `dbe_tests` instead - as you are adding it below. Otherwise, please explain why these are unrelated

2020-11-06 13:30 UTC, anton-malakhov approved these changes
LGTM, thanks!

2020-11-06 13:30 UTC, anton-malakhov commented on Tests/CMakeLists.txt
> +  add_custom_target(dbe_tests
rename as `dbe_test_all`?

2020-11-06 13:30 UTC, anton-malakhov commented on Tests/CMakeLists.txt
> +  add_dependencies(all_tests dbe4py-test)
merge with if section below

2020-11-06 14:39 UTC, igalink commented on Embedded/CMakeLists.txt
> +        DEPENDS DBEngine ${pydeps} mapd_java_components
Fixed

2020-11-06 14:39 UTC, igalink commented on Tests/CMakeLists.txt
> +  add_dependencies(all_tests dbe4py-test)
Done

2020-11-06 14:40 UTC, igalink commented on Tests/CMakeLists.txt
> +  add_custom_target(dbe_tests
renamed to dbe_all_tests

2020-11-06 14:42 UTC, igalink commented on Tests/CMakeLists.txt
> +  add_dependencies(dbe_tests dbe4py-test)
dbe4py-test runs only Python tests
dbe_all_tests runs C++ and Python tests related to dbe
dbe_tests renamed to dbe_all_tests

2020-11-06 21:57 UTC, ienkovich commented on Tests/CMakeLists.txt
> +  add_dependencies(dbe_tests dbe4py-test)
I still don't see how `all_tests` target runs C++ DBE tests.

2020-11-10 12:04 UTC, igalink commented on Tests/CMakeLists.txt
> +  add_dependencies(dbe_tests dbe4py-test)
if(ENABLE_CUDA)
  list(APPEND TEST_PROGRAMS GpuSharedMemoryTest)
elseif(ENABLE_DBE)
===>  list(APPEND TEST_PROGRAMS EmbeddedDatabaseTest)
endif()
...

add_custom_target(all_tests
...
===>    DEPENDS ${TEST_PROGRAMS} ProfileTest UtilTest RunQueryLoop StringDictionaryTest StringTransformTest StoragePerfTest
    USES_TERMINAL)

2020-11-10 13:29 UTC, ienkovich commented on Tests/CMakeLists.txt
> +  add_dependencies(dbe_tests dbe4py-test)
Why does enabled CUDA disable embedded tests?

2020-11-10 13:57 UTC, igalink commented on Tests/CMakeLists.txt
> +  add_dependencies(dbe_tests dbe4py-test)
the same condition in global CMakeLists. ENABLE_DBE does not take effect in case of GPU because GPU is not supported by DBE right now.

2020-11-10 14:29 UTC, ienkovich commented on Tests/CMakeLists.txt
> +  add_dependencies(dbe_tests dbe4py-test)
If DBE is not CUDA enabled yet then an attempt to configure with both DBE and CUDA should fail and it's OK to have such check in the root CMakeLists. It is inappropriate to have if-else statements to choose between CUDA and DBE, these options are logically independent. When the DBE is CUDA enabled we want to just remove the restriction from the root CMakeLists, not all over the sources. Please fix that in a separate patch.

2020-11-10 14:29 UTC, ienkovich approved these changes

2020-11-10 15:08 UTC, merged