Change DBHandler to split transport and query running
intel-ai/omniscidb pull request #119
Opened 2020-12-07 14:01 UTC by igalink

Draft to split transport and query running in DBHandler

2020-12-08 10:14 UTC, ienkovich requested changes
I cannot build this branch with multiple errors in DBHandler.

2020-12-09 14:11 UTC, igalink commented
> I cannot build this branch with multiple errors in DBHandler.

Fixed

2020-12-09 16:05 UTC, ienkovich reviewed
I think the patch looks good enough. Let's commit as long as unit tests pass.

2020-12-16 11:35 UTC, anmyachev commented
@ienkovich can we merge this PR?

2020-12-16 12:05 UTC, ienkovich commented
As I said, this PR is ok to merge if it passes all tests.

2020-12-16 12:09 UTC, anmyachev commented
@ienkovich where can I see the status of the tests?

2020-12-16 12:16 UTC, ienkovich commented
That's what Galina should let us know.

2020-12-16 12:21 UTC, anmyachev commented
Thanks @ienkovich. 

@igalink  can you share status with us?
> @ienkovich where can I see the status of the tests?

2020-12-16 13:42 UTC, igalink commented
Tests has not passed yet. I'm fixing issue with read_csv python test.

2020-12-24 10:16 UTC, fexolm commented on Embedded/DBEngine.cpp
> +    auto catalog = sys_cat.switchDatabase(db_name, user.userName);
`catalog` seems to be unused, also, it looks like we could avoid use `auto &user` here

2020-12-24 10:16 UTC, fexolm commented on Embedded/DBEngine.cpp
> +  mapd::shared_ptr<DBHandler> db_handler_;
is there any reason to use mapd::shared_ptr only in that place?

2020-12-24 10:16 UTC, fexolm commented on Embedded/DBEngine.cpp
> -      g_enable_union = std::stoi(value);
where all those options are configured now?

2020-12-24 10:16 UTC, fexolm commented on QueryEngine/Descriptors/RelAlgExecutionDescriptor.cpp
> +    : results_(std::make_shared<ResultSet>(std::vector<TargetInfo>{},
do we need an empty result? why?

2020-12-24 10:16 UTC, fexolm commented on QueryEngine/Descriptors/RelAlgExecutionDescriptor.h
> +  RType getResultType() const { return type_; }
why do we need that mutability support now?

2020-12-24 11:43 UTC, ienkovich approved these changes
LGTM!

2020-12-24 11:43 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +              prog_config_opts.db_leaves,
That would be a general improvement for DBHandler. Nice to have but not related to the implemented feature.

2020-12-24 11:43 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +  mapd::shared_ptr<DBHandler> db_handler_;
This is to support older Thrift versions.

2020-12-24 11:43 UTC, ienkovich commented on Embedded/DBEngine.cpp
> -      g_enable_union = std::stoi(value);
We now use CommandLineOptions in init method to configure all parameters.

2020-12-24 11:43 UTC, ienkovich commented on QueryEngine/Descriptors/RelAlgExecutionDescriptor.cpp
> +    : results_(std::make_shared<ResultSet>(std::vector<TargetInfo>{},
ExecutionResult is supposed to have a result set. There are many places in the code where ExecutionResult is constructed with the empty result set, we just add a special constructor for convenience.

2020-12-24 11:43 UTC, ienkovich commented on QueryEngine/Descriptors/RelAlgExecutionDescriptor.h
> +  RType getResultType() const { return type_; }
We now use ExecutionResult as an output parameter and have to modify it.

2020-12-25 11:29 UTC, fexolm approved these changes

2020-12-25 17:55 UTC, igalink commented on Embedded/DBEngine.cpp
> +    auto catalog = sys_cat.switchDatabase(db_name, user.userName);
Fixed

2021-02-04 15:40 UTC, ienkovich commented on Embedded/Python/dbe.pyx
> +        cmd_str = cmd_str.replace("_", "-")
This replacement should affect keys only. E.g. for `--data=data_tmp` you would get `--data=data-tmp` which is not the desired behavior.

2021-02-04 21:39 UTC, igalink commented on Embedded/Python/dbe.pyx
> +        cmd_str = cmd_str.replace("_", "-")
Fixed

2021-02-05 10:17 UTC, ienkovich approved these changes

2021-02-05 10:43 UTC, merged