Standalone build update
intel-ai/omniscidb pull request #120
Opened 2020-12-10 12:39 UTC by kurapov-peter

Note: `make all_tests` didn't finish for me.

2020-12-10 13:48 UTC, ienkovich requested changes

2020-12-10 13:48 UTC, ienkovich commented on README.md
> +# Engine standalone build
This build option is not specifically for the embedded engine, you get the regular server as well. You also don't need to go this way to get the embedded engine and can simply using -DENABLE_DBE=ON. So, I would call this section 'build in conda environment` or similar.

2020-12-10 13:48 UTC, ienkovich commented on README.md
> +Engine standalone (resides in "modin" branch) build requires conda installation:
We shouldn't mention our working branches in the documentation. All related changes are pushed into master branch sooner or later. Also, none of our features require conda. We just use conda for easier dependencies installation.

2020-12-10 13:48 UTC, ienkovich commented on README.md
> +`git checkout modin`
This shouldn't be in build instruction.

2020-12-10 13:48 UTC, ienkovich commented on README.md
> +# Engine standalone unit testing
Build in conda environment doesn't change testing procedure. The embedded engine also doesn't have any special procedures. So, this section is not needed.

2020-12-10 16:00 UTC, kurapov-peter commented on README.md
> +# Engine standalone unit testing
I left the section as is, but joined with general one. Should I remove it completely? I haven't found any mention of how to run it in the readme.

2020-12-22 13:58 UTC, ienkovich approved these changes

2020-12-22 16:12 UTC, merged