Add option to set Monday as first day of week
intel-ai/omniscidb pull request #125
Opened 2021-01-26 13:54 UTC by abykovsk

2021-01-26 16:15 UTC, ienkovich requested changes
I'd propose to use 'first-weekday' instead of 'first-dow', it's more self-describing and matches the name of a parameter in Linux locale.

We also need a unit test for this new feature.

2021-01-28 13:43 UTC, ienkovich commented on Tests/ExecuteTest.cpp
> +    g_monday_first_weekday = true;
The patch is great! Just one comment: you should store the original `g_monday_first_weekday` into temp and restore it after your tests; otherwise, you might break other tests.

2021-02-03 07:51 UTC, Garra1980 commented
Is it good to go?

2021-02-03 10:06 UTC, ienkovich approved these changes

2021-02-03 11:32 UTC, merged