Map Omnisci exceptions to Python exceptions in DBE
intel-ai/omniscidb pull request #149
Opened 2021-04-08 10:52 UTC by igalink

Map Omnisci exceptions to Python exceptions in DBE #2861

I decided to not process all the list of the omnisci exceptions in the DBE and use only the basic ones. The reason is that the list of exceptions is large and requires linking many files, since they are not included in one header. But they are inherited from the base std::exception, which allows us to get the error string on the Python side.
Below is a list of omnisci exceptions:

TException
TTransportException
InvalidParseRequest
CudaErrorException
OutOfMemory
TooBigForSlab
ForeignStorageException
FailedToCreateSlab
PostEvictionRefreshException(e);
GeoTypesError
InsufficientBufferSizeException
GeoImportException
ArrowImporterException
QueryExecutionError
QueryMustRunOnCpu
WatchdogException
QueryMustRunOnCpu
ColumnarConversionNotSupported
TooManyLiterals
ReductionRanOutOfSlots
OverflowOrUnderflow
CompilationRetryNewScanLimit
NativeExecutionError
ExtensionFunctionBindingError
FailedToCreateBitmap
ParseIRError
CardinalityEstimationRequired
CompilationRetryNoLazyFetch
SpeculativeTopNFailed
StreamingTopNNotSupportedInRenderQuery
QueryNotSupported
RowSortException
SpeculativeTopNFailed
CompilationRetryNoCompaction
StreamingTopNOOM
OutOfHostMemory
OutOfRenderMemory
SringConstInResultSet
TableMustBeReplicated
HashJoinFail
TooManyHashEntries
FailedToJoinOnVirtualColumn
FailedToFetchColumn
OverlapsHashTableTooBig
NeedsOneToManyHash

2021-04-08 10:58 UTC, Garra1980 commented on Embedded/DBEngine.cpp
> +#include "gen-cpp/OmniSci.h"
What exactly we need it for?

2021-04-08 11:00 UTC, Garra1980 commented on Embedded/DBEngine.cpp
> +    throw;
Do we need this section really? Or it can be merged with next one?

2021-04-08 11:16 UTC, ienkovich reviewed
Where is `std::exception` transformed into python error? Please add some python tests.

2021-04-08 11:30 UTC, igalink commented on Embedded/DBEngine.cpp
> +#include "gen-cpp/OmniSci.h"
TException decrarated here and it is not inherited from the std::exception

2021-04-08 11:38 UTC, igalink commented on Embedded/DBEngine.cpp
> +    throw;
I have highlighted the QueryExecutionError since it is clearly an 
 external omnisci exception. This line can be removed as well as the following it, in any case, the basic std exceptions will be caught in Python. I decided to highlight them because this is a gateway for all omnisci exceptions and here you can additionally process them if necessary.

2021-04-08 11:41 UTC, igalink commented
> Where is `std::exception` transformed into python error? Please add some python tests.

Cython cannot throw C++ exceptions, or catch them with a try-except statement, but it is possible to declare a function as potentially raising an C++ exception and converting it into a Python exception. For example,

cdef extern from "some_file.h":
    cdef int foo() except +


C++ | Python

bad_alloc | MemoryError
bad_cast | TypeError
bad_typeid | TypeError
domain_error | ValueError
invalid_argument | ValueError
ios_base::failure | IOError
out_of_range | IndexError
overflow_error | OverflowError
range_error | ArithmeticError
underflow_error | ArithmeticError
(all others) | RuntimeError

2021-04-08 16:46 UTC, ienkovich requested changes
Overall it looks like we need to transform `apache::thrift::TException` into `std::runtime_error` in a couple of places. Putting `catch (...)` everywhere is a bad practice meaning you don't have a well-defined API, please avoid it. Also please don't catch exceptions just to re-throw them.

2021-04-08 16:46 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +    throw;
The list of exceptions you posted in your first comment consists mostly of internally used exceptions, they don't leave the `DBHandler`. `DBHandler` catches all exceptions and throws `TOmniSciException` instead.

2021-04-08 16:46 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +  } catch (...) {
Do you have any example of an exception that should be handled here? AFAIK OmniSci doesn't use exception not based on `std::exception` or `apache::thrift::TException`.

2021-04-08 16:46 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +  } catch(...) {
Here only `std::runtime_error` can be caught and we don't need to catch it.

2021-04-08 16:46 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +  } catch(...) {
`getTableDetails` throws `std::runtime_error` only. But actually, I would replace it with `CHECK` because it looks like a revealed metadata inconsistency.

2021-04-08 16:46 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +    return engine->setDatabase(db_name);
Only `std::runtime_error` can be caught here and we don't need it.

2021-04-08 16:46 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +    return engine->login(db_name, user_name, password);
This is another case where thrift exception should be transformed into `std::exception`. We can do it here or in `DBEngineImpl` but shouldn't `catch(...)`.

2021-04-08 16:46 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +    return cursor->getColCount();
This method doesn't throw.

2021-04-08 16:46 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +    return cursor->getRowCount();
This method doesn't throw.

2021-04-08 16:46 UTC, ienkovich commented on Embedded/DBEngine.cpp
> -  return cursor->getNextRow();
This method doesn't throw.

2021-04-08 16:46 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +    return cursor->getColType(col_num);
This method doesn't throw.

2021-04-08 16:46 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +    return cursor->getArrowRecordBatch();
This method doesn't throw.

2021-04-08 16:46 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +    throw std::runtime_error(ex.what());
I propose to use the virtual `printTo` method which prints both an exception type and an error message.

2021-04-08 18:06 UTC, igalink commented
> Overall it looks like we need to transform `apache::thrift::TException` into `std::runtime_error` in a couple of places. Putting `catch (...)` everywhere is a bad practice meaning you don't have a well-defined API, please avoid it. Also please don't catch exceptions just to re-throw them.

What place do you mean? What if after the next commit their number increases?
Catching all exceptions in this case is necessary in order not to cause an unrecognized sigfault in python, precisely because we really do not have a good API for exceptions.

2021-04-08 18:53 UTC, igalink commented on Embedded/DBEngine.cpp
> +  } catch (...) {
You are right, at the moment it is. But there is no guarantee that this will not change. All exceptions are caught here for the stable operation of the calling application. This idea is not new and I don't see anything strange here. In addition, it was originally planned to catch all custom exceptions here and propagate them into the same custom ones in python. But I came to the same conclusion: Exceptions are mostly internal. Therefore, I found external ones and made one handler for all functions. This allows you not to worry about changing the implementation in the future. Also, if necessary, you can add new exceptions and control what goes into python.

2021-04-08 18:57 UTC, igalink commented on Embedded/DBEngine.cpp
> +  } catch(...) {
I prefer unified exception handling for all public functions (see comment above).

2021-04-08 19:02 UTC, igalink commented on Embedded/DBEngine.cpp
> +    throw std::runtime_error(ex.what());
What do you mean? PrintTo from GoogleTest or just to add an exception type to the message?

2021-04-09 00:01 UTC, igalink commented on Embedded/DBEngine.cpp
> +    return cursor->getArrowRecordBatch();
I found at least one place where an exception is thrown: std::runtime_error in the ArrowResultSetConverter::getArrowBatch

2021-04-09 00:17 UTC, igalink commented on Embedded/DBEngine.cpp
> +    return engine->setDatabase(db_name);
TException also could be thrown in case of invalid session

2021-04-09 01:03 UTC, igalink commented
After some thought, I decided that in this case the targeted approach to exception handling is preferable. So I changed the code as per the comments. But TException must be caught in all functions that call the DBHandler, since it can be thrown even when searching for a session which can become invalid for example in case of failed authentication.
In additional I found that when the session was killed, the destructor throws an exception that leads to a core dump and also does not free resources, does not delete temporary files. So I add the catcher for TException in the "reset".
Also a couple of forgotten features have been added to python.

2021-04-09 07:46 UTC, Garra1980 commented on Embedded/Python/dbe.pyx
> +    def setDatabase(self, db_name):
Separate PR?

2021-04-09 07:47 UTC, Garra1980 commented on Embedded/DBEngine.cpp
> +        //scip exception in case of invalid session
skip

2021-04-09 08:07 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +        //scip exception in case of invalid session
'Ignore invalid session error'?

2021-04-09 08:21 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +  } catch (const apache::thrift::TException& ex) {
We can catch it in `DBEngineImpl::sql_execute_dbe` and avoid three `try/catch` blocks (in `executeDDL`, `executeDML` and `executeRA`). I'd generally prefer to have exception transformations in `DBEngineImpl` to keep `DBEngine` a simple wrapper with all logic implemented in `DBEngineImpl`.

2021-04-09 08:27 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +#include "gen-cpp/OmniSci.h"
Just looked into the thrift codes and found: https://github.com/apache/thrift/blob/master/lib/cpp/src/thrift/Thrift.h#L76
So if we handle `std::exception` based exceptions already then we might need no additional handling for them here.

2021-04-09 10:16 UTC, igalink commented on Embedded/Python/dbe.pyx
> +    def setDatabase(self, db_name):
This is too little for a new review. In addition, the login function is used in the TException test.

2021-04-09 10:19 UTC, igalink commented on Embedded/DBEngine.cpp
> +        //scip exception in case of invalid session
In the destructor, this session doesn't really matter. This event was logged earlier.

2021-04-09 10:20 UTC, igalink commented on Embedded/DBEngine.cpp
> +  } catch (const apache::thrift::TException& ex) {
agree, will do

2021-04-09 12:26 UTC, igalink commented on Embedded/DBEngine.cpp
> +  } catch (const apache::thrift::TException& ex) {
Done

2021-04-09 17:22 UTC, Garra1980 commented on Embedded/DBEngine.cpp
> +      try {
Why this change - formatting?

2021-04-09 21:37 UTC, igalink commented on Embedded/DBEngine.cpp
> +#include "gen-cpp/OmniSci.h"
You are right, it handled

2021-04-09 21:56 UTC, igalink commented on Embedded/DBEngine.cpp
> +#include "gen-cpp/OmniSci.h"
Reverted TException handling.
But now this PR does not match the title at all

2021-04-09 21:58 UTC, igalink commented on Embedded/DBEngine.cpp
> +      try {
because an additional try/catch block

2021-04-12 19:59 UTC, ienkovich approved these changes

2021-04-12 22:32 UTC, merged