FSI fix setNulls
intel-ai/omniscidb pull request #164
Opened 2021-05-26 10:44 UTC by fexolm

2021-05-26 11:39 UTC, ienkovich requested changes

2021-05-26 11:39 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +          auto resWithOffset = resultData + offset;
Looks like this should be moved three lines down where the real offset value is available.

2021-05-26 11:39 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
>      if (typeSize == 4) {
Due to previously found problem with `bool` type let's check here the type is float.

2021-05-26 11:39 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> -      setNullValues<double>(fragments, arr_col_chunked_array);
Let's check here type size is 8 (arrow supports 2-byte float type and we might want to in the future).

2021-05-26 11:39 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +              auto is_null = (~bitmap_data[bitmap_idx] >> bitmap_offset) & 1;
I'd move `~bitmap_data[bitmap_idx]` out from the loop. I think compilers cannot always disambiguate it with `dest[bitmap_offset]`.

2021-05-26 11:39 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +            for (int8_t bitmap_offset = 0; bitmap_offset < 8; ++bitmap_offset) {
Can compilers vectorize it on AVX512 using the bitmap value as a mask? Should we help it?

As for scalar code, full unroll helps to remove shifts.

2021-05-26 11:39 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +            arr_col_chunked_array = replaceNullValues(column_type, arr_col_chunked_array);
There is `arr_col_chunked_array->null_count()` call below which would now always return 0 instead of a real NULLs count.

2021-05-26 14:20 UTC, fexolm commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +          auto resWithOffset = resultData + offset;
Fixed

2021-05-26 14:20 UTC, fexolm commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
>      if (typeSize == 4) {
Fixed

2021-05-26 14:20 UTC, fexolm commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +              auto is_null = (~bitmap_data[bitmap_idx] >> bitmap_offset) & 1;
Fixed

2021-05-31 15:04 UTC, ienkovich approved these changes

2021-05-31 15:07 UTC, merged