Windows omniscidbe support
intel-ai/omniscidb pull request #165
Opened 2021-06-08 18:05 UTC by igalink

2021-06-08 19:46 UTC, Garra1980 commented on OSDependent/Windows/omnisci_path.cpp
> +  std::cout << "Abs path: " <<  abs_exe_path << std::endl;
Should be removed

2021-06-08 19:49 UTC, Garra1980 commented on QueryEngine/RelAlgExecutor.cpp
> +  return ErrorInfo();
This should be changed

2021-06-09 13:19 UTC, ienkovich requested changes

2021-06-09 13:19 UTC, ienkovich commented on QueryEngine/GroupByAndAggregate.cpp
> +      auto res = int(_BitScanForward(&index, (unsigned long)chosen_bytes) ? index + 1 : 0);
It's better to use `_BitScanForward64` for a 64-bit value than to shrink the value to a 32-bit type.

2021-06-09 13:19 UTC, ienkovich commented on QueryEngine/RelAlgExecutor.cpp
> +  return ErrorInfo();
Right. Since `ErrorInfo` has only two fields, all you need to do is to remove `.code =  ` and `.desctiption = `.

2021-06-09 13:19 UTC, ienkovich commented on QueryEngine/RuntimeFunctions.h
> +extern "C" uint64_t agg_count(uint64_t* agg, const int64_t);
Why is it required here on Windows?

2021-06-09 13:19 UTC, ienkovich commented on Shared/funcannotations.h
> +__attribute__((always_inline)) __attribute__((__visibility__("protected")))
The formatting looks wrong here. Please make sure the whole patch is formatted with `clang-format` to simplify rebases over the master in the future.

2021-06-09 13:19 UTC, ienkovich commented on ThirdParty/sqlite3/sqlite3.c
> +
Remove this change.

2021-06-09 13:19 UTC, ienkovich commented on scripts/mapd-deps-conda-dev-env.yml
> +#  - defaults
Shouldn't we have a separate file for Windows?

2021-06-09 14:09 UTC, igalink commented on QueryEngine/RuntimeFunctions.h
> +extern "C" uint64_t agg_count(uint64_t* agg, const int64_t);
Without this definition llvm unable to find agg_count function.

2021-06-09 17:00 UTC, ienkovich commented on QueryEngine/RuntimeFunctions.h
> +extern "C" uint64_t agg_count(uint64_t* agg, const int64_t);
`agg_count` is in the runtime module. How does this declaration affect it? It might be `ALWAYS_INLINE` fix or `DEBUG_JIT` which helped. Could you please check that this declaration is really required? There are many other runtime functions that are not declared here.

2021-06-10 10:15 UTC, Garra1980 commented on scripts/mapd-deps-conda-dev-env.yml
> +#  - defaults
Right, these changes should not work for Linux, I don't quite understand how it appeared in this PR. I don't know whether there is some ability to specify conditional dependencies. We should check this and if not - create separate file

2021-06-10 10:17 UTC, Garra1980 commented on Catalog/SysCatalog.cpp
> +void SysCatalog::initDB(bool is_new_catalog) {
Do we really need all those changes with is_new_catalog?

2021-06-10 10:18 UTC, Garra1980 commented on DataMgr/ForeignStorage/ForeignDataWrapperFactory.cpp
> +#ifdef ENABLE_IMPORT_PARQUET
This should go to master branch btw

2021-06-10 10:20 UTC, Garra1980 commented on ImportExport/Importer.cpp
> +#ifdef _MSC_VER
I realized that here we should check whether folly library is used

2021-06-10 10:22 UTC, Garra1980 commented on OSDependent/Windows/omnisci_path.cpp
> +#ifdef CONDA_BUILD
I believe here we should check conda_build and windows and else case should be left as it was earlier - abs_exe_dir.parent_path();

2021-06-11 11:55 UTC, ienkovich commented on Catalog/SysCatalog.cpp
> +void SysCatalog::initDB(bool is_new_catalog) {
That doesn't look right. 
1. Catalog is created per database, therefore is_new_db and is_new_catalog refer to the same thing. SysCatalog tables creation doesn't depend on this flag, this flag is passed to `createDatabse` to create the default database.
2. In `createDatabase` method `getCatalog` is called twice. The first time it is called with `is_new_db=true`, then Catalog object is removed and recreated with `is_new_db=false` to trigger database migration. I don't see why you want to call it with `is_new_db=true` twice. Renaming also looks irrelevant. Also, I don't see how it is related to Windows build.

2021-06-11 13:08 UTC, igalink commented on scripts/mapd-deps-conda-dev-env.yml
> +#  - defaults
Igor, first of all, this change from your commit. So the question is for you. As for the build for Linux... I created the conda environment using this yml, made the build and tested it before putting the PR

2021-06-11 13:09 UTC, igalink commented on CMakeLists.txt
> -  add_definitions("-D__STDC_FORMAT_MACROS=1")
Igor, the question is for you.

2021-06-11 13:09 UTC, igalink commented on CMakeLists.txt
> +  #add_compile_options("-fno-semantic-interposition")
Igor, the question is for you

2021-06-11 13:09 UTC, igalink commented on CMakeLists.txt
> +  #include_directories(SYSTEM "$ENV{CONDA_BUILD_SYSROOT}/usr/include")
Igor, the question is for you

2021-06-11 13:15 UTC, igalink commented on QueryEngine/RuntimeFunctions.h
> +extern "C" uint64_t agg_count(uint64_t* agg, const int64_t);
Without this change, I kept getting an "access violation" when trying to call a function by pointer. I have not tested similar functions and this is my oversight. I will try to make it in time.

2021-06-11 15:23 UTC, Garra1980 commented on scripts/mapd-deps-conda-dev-env.yml
> +#  - defaults
My commit was in branch dedicated to windows build and this one should work for Linux. There were no assumption that all my changes for windows should fit modin branch as is. In any case we usually don't leave commented code in PRs.

2021-06-11 15:25 UTC, Garra1980 commented on ImportExport/CMakeLists.txt
> +install(TARGETS StreamImporter KafkaImporter DESTINATION bin)
Let's drop this so far at all. It was made only for specific Windows build of dbe

2021-06-11 15:26 UTC, Garra1980 commented on CMakeLists.txt
> +#TODO: Remove. My ccache doesn't work on Windows for some reasons
yes, this should be removed

2021-06-11 15:28 UTC, Garra1980 commented on CMakeLists.txt
> +  #include_directories(SYSTEM "$ENV{CONDA_BUILD_SYSROOT}/usr/include")
I was expecting this and similar questions before PR is published. This one should be checked, probably removed for both Linux and Windows

2021-06-11 15:29 UTC, Garra1980 commented on CMakeLists.txt
> +  #add_compile_options("-fno-semantic-interposition")
this and above is only for Windows I guess, again I'm surprised it came in PR as is.

2021-06-11 15:35 UTC, igalink commented on CMakeLists.txt
> +  #include_directories(SYSTEM "$ENV{CONDA_BUILD_SYSROOT}/usr/include")
Just set the task more clearly so as not to be disappointed in expectations.

2021-06-11 18:26 UTC, igalink commented on OSDependent/Windows/omnisci_path.cpp
> +  std::cout << "Abs path: " <<  abs_exe_path << std::endl;
removed

2021-06-11 18:29 UTC, igalink commented on Shared/funcannotations.h
> +__attribute__((always_inline)) __attribute__((__visibility__("protected")))
Fixed

2021-06-11 18:30 UTC, igalink commented on ThirdParty/sqlite3/sqlite3.c
> +
Done

2021-06-11 18:31 UTC, igalink commented on scripts/mapd-deps-conda-dev-env.yml
> +#  - defaults
Separate file for Windows added: scripts/mapd-deps-conda-windows.yml

2021-06-11 18:32 UTC, igalink commented on Catalog/SysCatalog.cpp
> +void SysCatalog::initDB(bool is_new_catalog) {
Commit reverted

2021-06-11 18:34 UTC, igalink commented on Catalog/SysCatalog.cpp
> +  cat = getCatalog(db, is_new_catalog);
Commit reverted

2021-06-11 18:35 UTC, igalink commented on ImportExport/CMakeLists.txt
> +install(TARGETS StreamImporter KafkaImporter DESTINATION bin)
Done

2021-06-11 18:36 UTC, igalink commented on QueryEngine/GroupByAndAggregate.cpp
> +      auto res = int(_BitScanForward(&index, (unsigned long)chosen_bytes) ? index + 1 : 0);
Done

2021-06-11 18:45 UTC, igalink commented on Embedded/test/test_exceptions.py
> +#    assert "Division by zero" in str(excinfo.value)
The message is different. I think it broken because changes in the getErrorDescription function.  So it could be reverted when getErrorDescription refactored for Windows

2021-06-11 18:46 UTC, igalink commented on ImportExport/Importer.cpp
> +#ifdef _MSC_VER
Done

2022-02-03 10:07 UTC, ienkovich commented
Outdated

2022-02-03 10:07 UTC, closed without merging