Remove unnecessary memory accesses from CPU codegen
intel-ai/omniscidb pull request #194
Opened 2021-11-08 11:38 UTC by de1iza

2021-11-08 11:40 UTC, de1iza commented
It speeds up lauchCpuCode stage by around 30% for the following query for row-wise output:
```sql
SELECT x*2 FROM table;
```

2021-11-25 14:17 UTC, ienkovich requested changes

2021-11-25 14:17 UTC, ienkovich commented on QueryEngine/NativeCodegen.cpp
> +          check_interrupt_func->addAttribute(~0U, llvm::Attribute::ReadOnly);
There is a special optimization pass that sets attributes for internal functions (see AnnotateInternalFunctionsPass). Can we set this attribute there for consistency?

2021-11-25 14:17 UTC, ienkovich commented on QueryEngine/QueryTemplateGenerator.cpp
> +      PAS = Attributes::get(mod->getContext(), 10U, B);
Could you please explain which parameter this attribute is applied to?

2021-11-30 14:08 UTC, merged