Fix for issue #198 Output buffer initialization overhead
intel-ai/omniscidb pull request #199
Opened 2021-11-12 15:47 UTC by sign60intel

2021-11-14 09:51 UTC, sign60intel commented
results of sanity_tests:
 
 without this fix:

```
92% tests passed, 5 tests failed out of 64

Label Time Summary:

sanity    = 3331.03 sec*proc (64 tests)

Total Test time (real) = 3331.48 sec

The following tests FAILED:
          3 - ImportExportTest (Failed)
          4 - ArrowCsvForeignStorageTest (Failed)
          7 - ExecuteTest (Failed)
          8 - ExecuteTestTemporaryTables (Failed)
         69 - UdfTest (Failed)
```

with this fix:
```
66% tests passed, 22 tests failed out of 64

Label Time Summary:
sanity    = 2305.89 sec*proc (64 tests)

Total Test time (real) = 2306.72 sec

The following tests FAILED:
          2 - UpdelStorageTest (Failed)
          3 - ImportExportTest (Failed)
          4 - ArrowCsvForeignStorageTest (Failed)
          5 - AlterTableDdlTest (Failed)
          7 - ExecuteTest (Failed)
          8 - ExecuteTestTemporaryTables (Failed)
          9 - GeospatialTest (Failed)
         15 - CachedHashTableTest (Failed)
         23 - ComputeMetadataTest (Failed)
         26 - TableFunctionsTest (Failed)
         28 - ParallelExecutorsTest (Failed)
         30 - MigrationMgrTest (Failed)
         32 - TopKTest (Failed)
         36 - DBObjectPrivilegesTest (Failed)
         39 - CtasUpdateTest (Failed)
         40 - CorrelatedSubqueryTest (Failed)
         44 - UpdateMetadataTest (Failed)
         49 - ShowCommandsDdlTest (Failed)
         53 - ForeignTableDmlTest (Failed)
         61 - ShardedTableEpochConsistencyTest (Failed)
         65 - LoadTableTest (Failed)
         69 - UdfTest (Failed)

```

2021-11-21 11:35 UTC, sign60intel commented
The last version of this fix gives the same results on sanity_tests as without it, i.e.

```
92% tests passed, 5 tests failed out of 

Label Time Summary:
sanity    = 3359.51 sec*proc (64 tests)

Total Test time (real) = 3359.89 sec

The following tests FAILED:
          3 - ImportExportTest (Failed)
          4 - ArrowCsvForeignStorageTest (Failed)
          7 - ExecuteTest (Failed)
          8 - ExecuteTestTemporaryTables (Failed)
         69 - UdfTest (Failed)
 ```

2021-11-21 11:45 UTC, sign60intel commented
Timer results with this fix:
```
449ms total duration for executeRelAlgQuery
```
without it 
```
531ms total duration for executeRelAlgQuery
```

2021-11-22 09:57 UTC, fexolm commented on QueryEngine/QueryMemoryInitializer.cpp
> +      initColumnarGroups(query_mem_desc, buffer, init_agg_vals_, executor);
What if output_columnar, but not groupby?

2021-11-22 09:57 UTC, fexolm commented on QueryEngine/QueryMemoryInitializer.cpp
> +         result_set::fill_empty_key(
Does this code vectorize? If not, we could use the same approach, as we did here https://github.com/intel-ai/omniscidb/pull/208

2021-11-22 09:57 UTC, fexolm commented on QueryEngine/QueryMemoryInitializer.cpp
> +    (ra_exe_unit.groupby_exprs.size() > 1) ||
How could we have non group-by buffer in initGroubByBuffer function? :) Maybe we need to move that dispatch before we even call that function.

2021-11-22 13:03 UTC, sign60intel commented on QueryEngine/QueryMemoryInitializer.cpp
> +      initColumnarGroups(query_mem_desc, buffer, init_agg_vals_, executor);
this is the case from the test above

2021-11-22 13:07 UTC, sign60intel commented on QueryEngine/QueryMemoryInitializer.cpp
> +    (ra_exe_unit.groupby_exprs.size() > 1) ||
There are two calls of initGroupByBuffer so this approach causes the code duplication.

2021-11-22 13:08 UTC, sign60intel commented on QueryEngine/QueryMemoryInitializer.cpp
> +         result_set::fill_empty_key(
Maybe this is the issue for another PR do not tangle this

2021-11-22 16:47 UTC, ienkovich reviewed
I don't understand the logic of these changes. Could you please explain why we can skip init for columnar format and cannot skip it for the non-columnar case? It's also not clear why we need to change anything for the non-columnar case (the original perf problem is for columnar output).

2021-11-22 17:45 UTC, sign60intel commented
@ienkovich 
I've changed 
```
data = {"a": [2] * 300000000}
```
to
```
data = {"a": [2] * 300000017}
```
and got the following results
without this fix
```
550ms total duration for executeRelAlgQuery
```
with this fix
```
518ms total duration for executeRelAlgQuery
```

2021-11-22 17:57 UTC, sign60intel commented
> I don't understand the logic of these changes. Could you please explain why we can skip init for columnar format and cannot skip it for the non-columnar case? It's also not clear why we need to change anything for the non-columnar case (the original perf problem is for columnar output).

Actually for the non-columnar case all initializations (see QueryMemoryInitializer::initRowGroups) are skipped besides  this
```
         result_set::fill_empty_key(
            buffer_ptr, key_count, query_mem_desc.getEffectiveKeyWidth());
```
that is responsible for the row determination in the result set 

I've investigated the source of initColumnarGroups and didn't see analogous code but the initialization loops only

2021-11-24 15:06 UTC, sign60intel commented
ExecuteTest with --enable-columnar-output shows the same result as without it

2021-11-24 21:21 UTC, ienkovich requested changes
Overall the patch looks good!

I left a few comments on code improvement. Also, please use clang-format for proper indent, trailing spaces, etc. It also would be nice to have a single squashed commit since the patch is quite small.

Since the key column is not used for columnar projections at least on CPU, I wonder if we should fill a new task to get rid of it at all. This would reduce memory consumption and speed-up query execution.

2021-11-24 21:21 UTC, ienkovich commented on QueryEngine/QueryMemoryInitializer.cpp
> +    if (is_groupby) {
I finally found out why we can skip initialization here. When we run CPU projection code, we always compute a number of matched rows. This number is then used for columnar output buffer compaction (see compactProjectionBuffersCpu). This means we would never read uninitialized keys. The proper condition for skipping initialization here then would be to check that the execution device is CPU and that QueryDescriptionType is Projection.

2021-11-24 21:21 UTC, ienkovich commented on QueryEngine/QueryMemoryInitializer.cpp
> +       const size_t key_count{query_mem_desc.getGroupbyColCount()};
This part looks correct but I don't like the code duplication we have here. Instead of copying a part of `initRowGroups` we can simply skip `memcpy` calls in the copied loop when QueryDescriptionType is Projection.

2021-11-25 08:00 UTC, sign60intel commented
@ienkovich 
I've added the line to the end of the script above

```
print(df.shape)
```

The result is
```
$ MODIN_EXPERIMENTAL=true MODIN_STORAGE_FORMAT=omnisci MODIN_ENGINE=native MODIN_OMNISCI_LAUNCH_PARAMETERS="enable-debug-timer=1, data=mytmp" python repro198.py
UserWarning: Distributing <class 'dict'> object. This may take some time.
(300000017, 1)
```

2021-11-26 19:04 UTC, ienkovich approved these changes
LGTM!

2021-11-26 19:19 UTC, fexolm approved these changes

2021-11-29 14:03 UTC, ienkovich commented on QueryEngine/QueryMemoryInitializer.cpp
> +  if (!query_mem_desc.hasKeylessHash() &&
I don't think this would be faster than vectorized code at least for small rows. I propose to commit the columnar part and either leave row initialization as is or work on it separately by building proper heuristics through performance experiments.

2021-11-29 19:38 UTC, sign60intel commented on QueryEngine/QueryMemoryInitializer.cpp
> +  if (!query_mem_desc.hasKeylessHash() &&
@ienkovich 
ok, I delete fix in row initialization

2021-11-29 20:04 UTC, ienkovich approved these changes

2021-11-29 20:12 UTC, merged