Novichkovg/arrow table conversion cont
intel-ai/omniscidb pull request #211
Opened 2021-11-24 17:49 UTC by novichkovg

This is a draft PR

2021-11-27 10:07 UTC, Garra1980 commented on Tests/CMakeLists.txt
> +add_executable(CachingFileMgrTest CachingFileMgrTest.cpp)
I'm wondering why changes in this CMakeLists are necessary?

2021-11-29 23:55 UTC, ienkovich requested changes
The functional part is mostly OK! Please follow comments and add some tests for join and group-by cases to improve coverage. You also need to have some tests with NULLs.

2021-11-29 23:55 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +void import_file(const std::string& file_name, const std::string& table_name)
Please use the following order:
 - helper functions
 - tests
 - main

2021-11-29 23:55 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +  testing::InitGoogleTest();
Use `testing::InitGoogleTest(&argc, argv);` to use gtest flags for tests filtering.

2021-11-29 23:55 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +  if (!fs::exists(fs::path{INPUT_CSV_FILE})) {
File existence check is done when the file is imported. Don't duplicate it here.

2021-11-29 23:55 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +  std::cout << "OPTIONS:    " << options_str <<std::endl;
Remove the print.

2021-11-29 23:55 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +//  ============
The comment is totally useless.

2021-11-29 23:55 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +} catch (...) {
Remove it. We don't throw unknown exceptions. Also, the default handler would probably give us more information than this print.

2021-11-29 23:55 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +    using arrow_col_type = typename traits<TYPE>::type;
1. Use proper naming for types
2. There are existing traits, you re-implement them.
`using ArrayType = arrow::NumericArray<typename arrow::CTypeTraits<TYPE>::ArrowType>;`

2021-11-29 23:55 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +  //  Basically, at std::static_pointer_cast<> we cast chunks[i] to a the
Please don't repeat the code in native English. Developers know what cast expressions do and see that TYPE is used as an underlying type for vector. Comment should shortly explain what the method does. E. g.
`// Compare column data with reference values.`

2021-11-29 23:55 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +  auto test_column = [&]<typename TYPE> (const std::vector<TYPE> & test_col, const std::shared_ptr<arrow::ChunkedArray> & column)
Propose naming change:
test_column => compare_column
test_sol => expected
column => actual

2021-11-30 12:27 UTC, novichkovg commented on Tests/CMakeLists.txt
> +add_executable(CachingFileMgrTest CachingFileMgrTest.cpp)
I did not touch this file at all.  Perhaps it came from the rebasing with modin branch.

2021-11-30 12:28 UTC, novichkovg commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +          for (size_t i = 0; i < c; i++) {
That change has been done awhile ago; I did it to remove warnings from the compiler.

2021-11-30 12:37 UTC, novichkovg commented on QueryEngine/ResultSetStorage.h
> +  // ALWAYS_INLINE
ALWAYS_INLINE pragma appears before method which is implemented in .cpp file rather than the header file.  In my opinion in this case there should be no such pragma at all as it is meaningless.  If you agree, I remove ALWAYS_INLINE.

2021-11-30 12:46 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +//  ============
It serves the purpose of spotting main() function in the bloat of code.  Faster to find, less strain for brain.

2021-11-30 12:47 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +} catch (...) {
Done.

2021-11-30 12:54 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  //  Basically, at std::static_pointer_cast<> we cast chunks[i] to a the
I added it to show the intent so that  fewer questions asked.

2021-11-30 12:55 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  auto test_column = [&]<typename TYPE> (const std::vector<TYPE> & test_col, const std::shared_ptr<arrow::ChunkedArray> & column)
Good suggestion!

2021-11-30 12:56 UTC, ienkovich commented on QueryEngine/ResultSetStorage.h
> +  // ALWAYS_INLINE
Attributes go with a declaration, they are not meaningless and this change is not related to implemented functionality anyway.

2021-11-30 13:01 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  auto test_column = [&]<typename TYPE> (const std::vector<TYPE> & test_col, const std::shared_ptr<arrow::ChunkedArray> & column)
I renamed it as suggested, and removed explaining comment as the function's name is self-explainatory.

2021-11-30 13:02 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  auto test_column = [&]<typename TYPE> (const std::vector<TYPE> & test_col, const std::shared_ptr<arrow::ChunkedArray> & column)
Done.

2021-11-30 13:07 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +    using arrow_col_type = typename traits<TYPE>::type;
I use traits to parametrize compile-time type selection.  For the `->raw_values()` call to work, I need to do appropriate casting, to an appropriate type.  How would I know what that type should be?  From my traits: I know the underlying type of the expected column and accordingly I deduce the underlying type of the actual column.  Hope this clarifies the code.

2021-11-30 13:16 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +//  =====================================================================
It is just a matter of style and personal preference.  In my view `======` separators give code better appearance and better structuring.

2021-11-30 13:28 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +#define INPUT_CSV_FILE "./embedded_db_test.csv"
I wish I could!  If I do so, things like this `"File not found: " INPUT_CSV_FILE ". Aborting\n" ` do not compile, that is the primary reason I used `#define` in the first place.

2021-11-30 13:28 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +          for (size_t i = 0; i < c; i++) {
Still should be removed from this PR as an unrelated change.

2021-11-30 13:31 UTC, ienkovich commented on Tests/CMakeLists.txt
> +add_executable(CachingFileMgrTest CachingFileMgrTest.cpp)
More reasons t drop these changes from the PR.

2021-11-30 13:33 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +#define INPUT_CSV_FILE "./embedded_db_test.csv"
You can use it with `<<`. Also, a file existence check is done during import, you don't need to duplicate it here.

2021-11-30 13:34 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +void create_table (std::string table_name, size_t chunk_size) {
This is a helper function either creates a table without chunks or creates a table with chunks. Hence two parameters: table_name and chunk_size.

```
  create_table ("test",         /*chunk_size=*/0);
  create_table ("test_chunked", /*chunk_size=*/4);

```

2021-11-30 13:36 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  if (!fs::exists(fs::path{INPUT_CSV_FILE})) {
Done.

2021-11-30 13:36 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +    using arrow_col_type = typename traits<TYPE>::type;
Here is how you can choose a proper arrow array type using arrow traits: `using ArrayType = arrow::NumericArray<typename arrow::CTypeTraits<TYPE>::ArrowType>`

2021-11-30 13:44 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  testing::InitGoogleTest();
I rendered the change you suggested, however it does not work as `boost::program_options` breaks command line args:

```
$ ./build/bin/EmbeddedDbTest --gtest_filter=DBEngine.ArrowTableChunked_Conversion1
Usage Error: unrecognised option '--gtest_filter=DBEngine.ArrowTableChunked_Conversion1'
Options:
  -h [ --help ]                     Print help messages
  -c [ --catalog ] arg (=tmp)       Directory path to OmniSci catalogs
  -p [ --calcite-port ] arg (=5555) Calcite port
  -o [ --columnar-output ] arg (=1) Enable columnar_output
```

2021-11-30 13:48 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  testing::InitGoogleTest();
Ah, it works if I init GoogleTest **before** parsing command lines.  I will remove the unnecessary comment.

2021-11-30 13:55 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  std::cout << "OPTIONS:    " << options_str <<std::endl;
Done.

2021-11-30 13:58 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  testing::InitGoogleTest();
To work, the code should look like this:
```
int main(int argc, char* argv[]) try {

  namespace fs = std::filesystem;

  testing::InitGoogleTest(&argc, argv);

  auto options_str = parse_cli_args(argc, argv);
  ... 
```
that is `testing::InitGoogleTest(&argc, argv);` must be executed before using `boost::program_options`.  Resolving.

2021-11-30 14:03 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +//  =====================================================================
Code shouldn't follow personal preferences. This would produce a mess where everyone uses its favorite ASCII markup as anchors all over the code. Consistency always beats personal taste.

2021-11-30 14:06 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +void create_table (std::string table_name, size_t chunk_size) {
You can add 'fragmen_size' parameter to `import_file` and make similar imports. We just have two functions doing similar things.

2021-11-30 14:12 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +  testing::InitGoogleTest();
You can follow other examples and add these flags:
```
// these two are here to allow passing correctly google testing parameters
desc.add_options()("gtest_list_tests", "list all test");
desc.add_options()("gtest_filter", "filters tests, use --help for details");
```

2021-11-30 14:16 UTC, novichkovg commented on QueryEngine/ResultSet.h
> +//  FOR DEBUGGING PUPROSES
The `ResultSet::inspectStorage(size_t n)` function served the purpose of looking into what's inside the underlying buffer, appropriately casted (hence templating of this function).  Also, it does not print entire buffer, it prints first `n` elements provided by the user.

I think it is useful, it definitely helped me with finding bugs.

2021-11-30 14:17 UTC, novichkovg commented on QueryEngine/ResultSet.h
> +#include <utility>  //  std::pair
Removed.

2021-11-30 14:17 UTC, novichkovg commented on QueryEngine/ResultSet.h
> +  //  returns vector of std::pair<chunk buffer ptr, chunk row count>
Fixed.

2021-11-30 14:18 UTC, novichkovg commented on QueryEngine/ResultSet.h
> +
Fixed.

2021-11-30 14:19 UTC, ienkovich commented on QueryEngine/ResultSetStorage.cpp
> +// ACCESSORS
OmniSci follows C++ Core Guidelines. Actually, it's not really strict and allows multiple options, it would be nice to make a coding guide some day.
https://docs.omnisci.com/v5.0.1/2_os_get_started.html#coding

2021-11-30 14:36 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +void import_file(const std::string& file_name, const std::string& table_name)
Frankly, I think all helper functions must be put in `helper` namespace. Where to keep them in the source file? -- I don't know, but if you say they should be at the top, I'll do that. The important thing is that there is determined place for them to reside.

2021-11-30 14:46 UTC, ienkovich commented on QueryEngine/ResultSet.h
> +//  FOR DEBUGGING PUPROSES
It's better to use some generic way instead of adding similar printers for classes that have an underlying buffer. You can simply do something like `x/10d buff_` in a debugger. In the code, you can do something like
`toString(std::vector<TYPE>(reinterpret_cast<TYPE*>(buff_), reinterpret_cast<TYPE*>(buff_) + n))`.

2021-11-30 14:49 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +#define INPUT_CSV_FILE "./embedded_db_test.csv"
Here I cannot do `<<`:   
```
std::string  create_query = "CREATE TEMPORARY TABLE "+table_name+" (t TEXT, i INT, bi BIGINT, d DOUBLE) "
                              "WITH (storage_type='CSV:" INPUT_CSV_FILE "'" + frag_size_param+");";
```

>Also, a file existence check is done during import, you don't need to duplicate it here.
Unfortunately, `import_file` function does not handle file absence well, that is why I added that file existence check.

2021-11-30 14:52 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +//  ============
>Having the main method at the end of each unit test file would work much better here for your purpose.
OK, let's go by sectioning source file then.  I will restructure the .cpp file as helpers/tests/main and remove unnecessary indicator of main().

2021-11-30 14:59 UTC, novichkovg commented on QueryEngine/ResultSetStorage.h
> +  // ALWAYS_INLINE
>Attributes go with a declaration, they are not meaningless and this change is not related to implemented functionality anyway.

OK, my question is: if I leave `ALWAYS_INLINE` in the function definition but don't provide function implementation in the header, will it is inlined?

2021-11-30 15:01 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +#define INPUT_CSV_FILE "./embedded_db_test.csv"
You can use `constexpr std::string_view` which should always concat OK using `+`.
Doesn't arrow give some readable message that the file is missing? The proper check place is the `import_file` then.

2021-11-30 15:14 UTC, ienkovich commented on QueryEngine/ResultSetStorage.h
> +  // ALWAYS_INLINE
This is a declaration, not a definition. If you use the inline attribute here then it will be inlined in all modules where both declaration and definition exist. I.e. in our case, it will be inlined only within `ResultSetStorage.o`. With LTO applied it can be inlined in other places too. Not all attributes require a function definition in a module to become useful, so the declaration is a better place for them (except cases when an attribute is definition specific, like `target` attribute).

2021-11-30 15:15 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +#define INPUT_CSV_FILE "./embedded_db_test.csv"
>You can use constexpr std::string_view which should always concat OK using +

Let me try that.  If works, go by `constexpr std::string_view`.

2021-11-30 15:35 UTC, novichkovg commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +          for (size_t i = 0; i < c; i++) {
> Still should be removed from this PR as an unrelated change.

I agree it is unrelated, but who will take care of it?  And when?

2021-11-30 15:51 UTC, novichkovg commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +          for (size_t i = 0; i < c; i++) {
> Typically in such cases separate PR should be created

OK, I reverted this to the original erroneous state, we will fix it by a separate PR. Resolving.

2021-11-30 15:57 UTC, Garra1980 commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +          for (size_t i = 0; i < c; i++) {
Thanks!

2021-11-30 16:00 UTC, novichkovg commented on QueryEngine/ResultSet.h
> +//  FOR DEBUGGING PUPROSES
>  In the code, you can do something like toString(std::vector<TYPE>(reinterpret_cast<TYPE*>(buff_), reinterpret_cast<TYPE*>(buff_) + n)).

Does it work, did you try that?

2021-11-30 16:08 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +#define INPUT_CSV_FILE "./embedded_db_test.csv"
OK, I tried `constexpr std::string_view INPUT_CSV_FILE = "./embedded_db_test.csv";`.  As a result I see:

```
    std::string  create_query = "CREATE TEMPORARY TABLE "+table_name+" (t TEXT, i INT, bi BIGINT, d DOUBLE) "
                                "WITH (storage_type='CSV:"+INPUT_CSV_FILE+"'"+frag_size_param+");";
```
-- fails to compile, then `throw std::runtime_error ("File not found: "+INPUT_CSV_FILE+". Aborting\n");` fails to compile
```
/nfs/site/home/gnovichk/shm/omniscidb/Embedded/EmbeddedDbTest.cpp:426:49: error: no match for 'operator+' (operand types are 'const char [17]' and 'const string_view' {aka 'const std::basic_string_view<char>'})
  426 |     throw std::runtime_error ("File not found: "+INPUT_CSV_FILE+". Aborting\n");
```
etc, etc.

Suggest that we stay with this `#define INPUT_CSV_FILE`, unless we want to open a can of worms and increase code bloat.

2021-11-30 16:15 UTC, novichkovg commented on QueryEngine/ResultSetStorage.cpp
> +// TODO: ADD CACHING TO ResultSetStorage::binSearchRowCount()
Moved the comment to `size_t ResultSetStorage::binSearchRowCount() const` function located in `ResultSetInteration.cpp` file (don't ask me why they put it there).

Resolving.

2021-11-30 16:17 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +//  ============
Restructuring is done. Resolving.

2021-11-30 16:20 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +void create_table (std::string table_name, size_t chunk_size) {
> You can add 'fragmen_size' parameter to import_file and make similar imports. We just have two functions doing similar things.

I am inclined to remove `import_file()` .  Do we need to test `DBEngine::importArrowTable(table_name, arrowTable);` function?  If not, I will remove `import_file()`

2021-11-30 16:24 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +void import_file(const std::string& file_name, const std::string& table_name)
I moved helper function into `helpers` namespace which is now at the upper portion of  the test source file.  Now these are invoked like this:
```auto options_str = helpers::parse_cli_args(argc, argv); ```

Resolving.

2021-11-30 16:28 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +//  =====================================================================
Code should follow Coding Standards.  Where possible, I follow Bloomberg BDE Coding Standards, in which these comments are used.  They make source code very readable and well structured, and this is the main reason for using these style of comments.

>  Consistency always beats personal taste.
Very true.  This is why I am convinced of the usefulness of Coding Standards.

2021-11-30 16:31 UTC, novichkovg commented on embedded_db_test.csv
> +t,i,bi,d
I agree, I just cannot decide on the proper place for the file.  I will defer relocating this file till the last moment, as I am frequently run the test.

2021-11-30 16:39 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +    using arrow_col_type = typename traits<TYPE>::type;
> Here is how you can choose a proper arrow array type using arrow traits: using ArrayType = arrow::NumericArray<typename arrow::CTypeTraits<TYPE>::ArrowType>

It worked, test passes.  Changing to Arrow type resolution version.

Resolving.

2021-11-30 16:53 UTC, novichkovg commented on QueryEngine/ResultSet.cpp
> +  retval.push_back({storage_->getUnderlyingBuffer() + storage_->getColOffInBytes(column_idx), storage_->binSearchRowCount()});
I tried `emplace_back` first but somehow it did not compile. So I resorted old-good `.push_back()`.  Let me try it again;  `emplace_back` works, I will change to `emplace_back`

2021-11-30 16:57 UTC, novichkovg commented on QueryEngine/ResultSet.cpp
> +  // std::cout
Removed. Resolving.

2021-11-30 17:03 UTC, ienkovich commented on QueryEngine/ResultSetStorage.h
> +  // ALWAYS_INLINE
```
$ cat 1.cpp
ALWAYS_INLINE int test2(int i);

int test2(int i) { return i; }

int test1(int i) { return test2(i); }
$ gcc -DALWAYS_INLINE= -S 1.cpp
$ grep call 1.s
        call    _Z5test2i
$ gcc -DALWAYS_INLINE='__attribute__((always_inline))' -S 1.cpp
$ grep call 1.s
```

2021-11-30 17:04 UTC, novichkovg commented on QueryEngine/ResultSet.cpp
> +  retval.push_back({storage_->getUnderlyingBuffer() + storage_->getColOffInBytes(column_idx), storage_->binSearchRowCount()});
Tried again and it did not compile.  Switching to 
```
  retval.emplace_back(std::make_pair(storage_->getUnderlyingBuffer() + storage_->getColOffInBytes(column_idx), storage_->binSearchRowCount()));
```
makes it compile, though.  Tests are passing, so resolving.

2021-11-30 17:07 UTC, ienkovich commented on QueryEngine/ResultSet.h
> +//  FOR DEBUGGING PUPROSES
Didn't try. It should work. Why not?

2021-11-30 17:09 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +  using arrow_buffer_t = std::shared_ptr<arrow::Buffer>;
Changed to 
```
  std::vector<std::shared_ptr<arrow::Buffer>> 
    values;

  std::shared_ptr<arrow::Buffer>              
    is_valid;
```
Resolving.

2021-11-30 17:10 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +void create_table (std::string table_name, size_t chunk_size) {
`import_file` tests arrow import and also can be used with any csv file while 'create_table' can only work with a hardcoded scheme. I'd prefer `import_file` usage.

2021-11-30 17:12 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +#define USE_TBB_PARALLEL_FOR
After more tests are added and we profile sequential and parallel execution, I will remove it.  This scaffold is needed for the time being.

2021-11-30 17:38 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +  const size_t entry_count = top_n_ < 0
I am not the author of this comparison: ` const size_t entry_count = top_n_ < 0` .  I can look into this issue, after everything is resolved.

2021-11-30 17:39 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +//#define VERBOSE  //  Enable if you wish to see the content of the chunks
`#define` macro seems to be vital and discussed in other places, along with other macros.  Resolving this as redundant.

2021-11-30 17:44 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +TEST(DBEngine, ArrowTableChunked_Conversion1) {
I see some opportunity for the code re-use (by creating a helper), but wouldn't it increase difficulty of the code comprehension?  If you see it is worthwhile doing, I'll go ahead and implement it.

2021-11-30 17:58 UTC, ienkovich commented on QueryEngine/ResultSet.cpp
> +  retval.push_back({storage_->getUnderlyingBuffer() + storage_->getColOffInBytes(column_idx), storage_->binSearchRowCount()});
Did you remove `{}` when tried `emplace_back`? The following code compiles fine:
```
#include <utility>
#include <vector>

void emplace(std::vector<std::pair<int *, int>> vec, int *ptr, int size) {
  vec.emplace_back(ptr, size);
}
```

2021-11-30 18:07 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +    v_arrow_num_array_sp(values.size(), nullptr);
> Please don't encode type into the variable name. Simple chunks will work.

Hmm... Somehow `chunk` seemed to be somewhat confusing, so I used that name for the array, with types.  I will think about a better name for it.

2021-11-30 18:52 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +      using numarray_t = arrow::NumericArray<ARROW_TYPE>;
`using numarray_t` -> `NumArray`

2021-11-30 18:58 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +#define INPUT_CSV_FILE "./embedded_db_test.csv"
TODO: investigate if we can use `import_file` for our purposes.

2021-11-30 21:35 UTC, novichkovg commented on QueryEngine/ResultSet.cpp
> +  retval.push_back({storage_->getUnderlyingBuffer() + storage_->getColOffInBytes(column_idx), storage_->binSearchRowCount()});
I think I forgot to remove curly braces, this is why the compiler was unhappy.  Will fix to correct version tomorrow.

2021-11-30 21:47 UTC, novichkovg commented on QueryEngine/ResultSetStorage.h
> +  // ALWAYS_INLINE
GitHub does not allow be to attach the files, so I will present the code.

Header file:
```
//  always_inline_test.h                                              -*-C++-*-
class A {
public:

	void m1();

	__attribute__((always_inline)) inline
	void m2();

	void print() const;
	int get_val() const;
private:

	int _i = 0;
};
//	END OF always_inline.h
```
Implementation file:
```
//  always_inline_test.cpp                                            -*-C++-*-
#include "always_inline_test.h"
#include <cstdio>

//	class A methods definitions
void A::m1() {
	_i++;
}

void A::m2() {
	_i--;
}


void A::print() const {
	printf("%d\n", _i);
}

int A::get_val() const {
	return _i;
}

//	end of class A methods definitions


int main() {
	A a;

	//a.m1();
	a.m2();
	//a.print();
	return a.get_val();
}
```
Assembly output invocation:
```
$ g++ -O3 always_inline_test.cpp -c -S -o - -masm=intel | c++filt | grep -vE '\s+\.'
``` 
Result:
```
A::m1():
.LFB12:
	add	DWORD PTR [rdi], 1
	ret
.LFE12:
.LC0:
A::print() const:
.LFB14:
	mov	esi, DWORD PTR [rdi]
	xor	eax, eax
	mov	edi, OFFSET FLAT:.LC0
	jmp	printf
.LFE14:
A::get_val() const:
.LFB15:
	mov	eax, DWORD PTR [rdi]
	ret
.LFE15:
main:
.LFB16:
	mov	eax, -1
	ret
.LFE16:
```

As we can see, indeed `void A::m2()` was inlined.  So I am confirming this, you are correct at least with respect to a single translation unit.

However, what are you going to do if you decide to use `A::m2()` in a different translation unit?  You have only header there, no definition of the method to be inlined.

2021-11-30 22:04 UTC, novichkovg commented on QueryEngine/ResultSetStorage.h
> +  // ALWAYS_INLINE
Now, if you move 
```
int main() {
	A a;

	//a.m1();
	a.m2();
	//a.print();
	return a.get_val();
}
```
to a different file, like this
```
//  always_inline_test.m.cpp                                          -*-C++-*-
#include "always_inline_test.h"
int main() {
	A a;

	// a.m1();
	a.m2();
	//a.print();
	return a.get_val();
}
```
and try to build you program from `.o` files, you will observe smth like this:
```
$ g++ -O3  always_inline_test.cpp -c 
$ g++ -O3  always_inline_test.m.cpp -c 
In file included from always_inline_test.m.cpp:2:
always_inline_test.h:8:7: warning: inline function ‘void A::m2()’ used but never defined
    8 |  void m2();
      |       ^~
always_inline_test.h: In function ‘int main()’:
always_inline_test.h:8:7: error: inlining failed in call to always_inline ‘void A::m2()’: function body not available
always_inline_test.m.cpp:7:6: note: called from here
    7 |  a.m2();
      |  ~~~~^~
```

2021-11-30 22:14 UTC, novichkovg commented on QueryEngine/ResultSetStorage.h
> +  // ALWAYS_INLINE
But, you might feel clever and move inlining to `.cpp` file, so that in `.h` you have 
```
	// __attribute__((always_inline)) inline
	void m2();
```
and in `always_inline_test.cpp` you have
```
__attribute__((always_inline)) inline
void A::m2() {
	_i--;
}
```
Then, you try to compile and see:
```
$ g++ -O3  always_inline_test.cpp -c 
$ g++ -O3  always_inline_test.m.cpp -c 
$ g++ always_inline_test.m.o always_inline_test.o 
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: always_inline_test.m.o: in function `main':
always_inline_test.m.cpp:(.text.startup+0x12): undefined reference to `A::m2()'
collect2: error: ld returned 1 exit status
```
Which is correct and expected behaviour.

So the suggestion to keep inlined function in the header file is quite sane, I should say.

2021-11-30 22:49 UTC, novichkovg commented on QueryEngine/ResultSetStorage.h
> +  // ALWAYS_INLINE
Personally, for the major I use inlining for performance reasons like this actual code
```
//	CHECKS IF QUEUE IS EMPTY
template <typename T, typename Alloc>    __attribute__((always_inline,hot)) inline
bool RingBufferQueue<T, Alloc>::empty() const
{
	return 	_items_count == 0;
}
```
So in my view, unless there are performance reasons to do inlining, it is better to move functions/methods to the implementation file and leave only there declaration in the header.  And let linker resolve the symbols at linking.

2021-12-01 01:01 UTC, ienkovich commented on QueryEngine/ResultSetStorage.h
> +  // ALWAYS_INLINE
You have compilation problems because you misuse the `inline` keyword. Inline function must have `inline` keyword in all translation units. `__attribute__((always_inline))` says this function should be always inlined, even if you use `-O0` optimization level (e.g. this is required for many AVX x86 intrinsics to work properly). It is not an error if you don't have the function body and cannot actually inline it (but it might be an error if you have a body but cannot inline it, e.g. it is a public function in a shared library).

Here is inline between compilation units:
```
$ cat test.h
__attribute__((always_inline)) int test1(int i);
$ cat test1.cpp
#include "test.h"

int test1(int i) { return i; }
$ cat test2.cpp
#include "test.h"

int main(int argc, const char **argv) { return test1(argc); }
$ gcc -O -flto test1.cpp test2.cpp
$ objdump -d a.out
...
0000000000001129 <main>:
    1129:       f3 0f 1e fa             endbr64
    112d:       89 f8                   mov    %edi,%eax
    112f:       c3                      retq
```

2021-12-01 14:08 UTC, novichkovg commented on QueryEngine/ResultSetStorage.h
> +  // ALWAYS_INLINE
Ah, you did two things:
1. specified `-flto` which I did not and
2. you fed source files to GCC rather than object files.

Which is different from what I did.

In my opinion, from the architectural standpoint it is incorrect to give a method `__attribute__((always_inline))` specifier in the header  and NOT to provide implementation in the header, simply because during the build you produce `.o` for each translation unit (often in parallel).

if you try to build your example like this:
```
$ g++ test1.cpp -c
$ g++ test2.cpp -c
$ g++ test1.o test2.o -o test
```
you will see a compilation error.

2021-12-01 14:34 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +#define INPUT_CSV_FILE "./embedded_db_test.csv"
`import_file` (modified to pass `fragment_size` into `importArrowTable`) breaks the tests, for instance:
```
[ RUN      ] DBEngine.ArrowTableChunked_Conversion1
/nfs/site/home/gnovichk/shm/omniscidb/Embedded/EmbeddedDbTest.cpp:206: Failure
Expected equality of these values:
  chunk_data[j]
    Which is: 0
  expected[i*chunk_size+j]
    Which is: 1
[  FAILED  ] DBEngine.ArrowTableChunked_Conversion1 (109 ms)
```

2021-12-01 14:59 UTC, novichkovg commented on QueryEngine/ResultSet.cpp
> +  retval.push_back({storage_->getUnderlyingBuffer() + storage_->getColOffInBytes(column_idx), storage_->binSearchRowCount()});
The cause of compiler's were present curly braces.  Removed them, program builds, tests pass.  Resolving.

2021-12-01 15:04 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +TEST(DBEngine, ArrowTableChunked_Conversion1) {
Moved repeated code to `ChunkedConversion()`.  Works, tests are passed. Resolving.

2021-12-01 15:15 UTC, novichkovg commented on QueryEngine/ResultSet.h
> +//  FOR DEBUGGING PUPROSES
removed `inspectStorage` function from the class.  Resolving.

2021-12-01 15:25 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +      is_valid = std::move(res).ValueOrDie();
Moved `std::shared_ptr<arrow::Buffer> is_valid` inside the loop. Resolving.

2021-12-01 15:53 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +  const size_t entry_count = top_n_ < 0
Inserted `  CHECK_LT(top_n_,0);` before that line.  Tests pass, resolving.

2021-12-01 16:24 UTC, novichkovg commented on embedded_db_test.csv
> +t,i,bi,d
made the following changes: 
```
#define TABLE6x4_CSV_FILE "../../Tests/EmbeddedDataFiles/embedded_db_test_6x4table.csv"
```
However, now (as expected) the test works only if it launched from `./build/bin` directory.  The proper way to go about it is to use some sort of `$OMNISCIDB_HOME`  environment variable.  Resolving.

2021-12-01 16:28 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +//  =====================================================================
I left some `// =======` comments to split source file into sections.  If it is still looks annoying, I will remove those.  Resolving for now.

2021-12-01 16:46 UTC, novichkovg commented on QueryEngine/ResultSetStorage.h
> +  // ALWAYS_INLINE
> I guess the idea here is that this method is private and will not be called from outside of a proper compilation unit.

That's the only possible scenario where it work, certainly.  However, **why** do it for `reduceOneSlotSingleValue` and `reduceOneSlot` functions and not do it for others?  They private.  I think that the true cause is much simpler: originally the implementation was in the header, but later devs moved it to `.cpp` file but forgot to remove `ALWAYS_INLINE` attribute.

2021-12-01 23:33 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +#define INPUT_CSV_FILE "./embedded_db_test.csv"
I found what was the problem of tests failure when `import_file()` was used to load data to table

Function `import_file()` reads the file and creates table with the following schema:
t: string
i: int64
bi: int64
d: double

However, the correct schema must be as follows
t: string
i: int32 # <= note the difference
bi: int64
d: double

This latter is the schema I create when read the table via SQL query.  

So with all likelyhood `importArrowTable()` is OK, the problem lies in creating correct schema when reading the table from a file via Arrow API.

@ienkovich , @Garra1980 please take a note of it.

2021-12-02 10:39 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +#define INPUT_CSV_FILE "./embedded_db_test.csv"
You can force column types using convert options

2021-12-02 16:37 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +#define INPUT_CSV_FILE "./embedded_db_test.csv"
> You can force column types using convert options
I created tests for both cases. Testing for correct schema (cols 1-3 only) has also been added.  Resolving.

2021-12-02 16:41 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +void create_table (std::string table_name, size_t chunk_size) {
`import_file()` was producing table with a different schema and that was the cause for test failures.  Adjusted the tests accordingly, added testing for correct schema.  Resolving.

2021-12-02 21:11 UTC, Garra1980 commented
Am I correct we need some complimentary changes in modin-project as well?

2021-12-02 21:31 UTC, ienkovich commented
Changes are required in `modin/experimental/core/execution/native/implementations/omnisci_on_native/partitioning/partition_manager.py` to utilize `getArrowTable` instead of `getArrowRecordBatch`. Changes are simple but we need to remain backward compatible.

2021-12-02 21:34 UTC, Garra1980 commented
Ah, thanks! So Gleb will also make a contribution to Modin-project ;)

2021-12-02 22:09 UTC, novichkovg commented
> Am I correct we need some complimentary changes in modin-project as well?

Basically I have this script
```
import sys
import pandas
import pyarrow

prev = sys.getdlopenflags()
sys.setdlopenflags(1 | 256) # RTLD_LAZY+RTLD_GLOBAL
from omniscidbe import PyDbEngine
sys.setdlopenflags(prev)

engine = PyDbEngine(data="omnitmp", enable_columnar_output=1)

df = pandas.DataFrame({"a": [4]*5, "b": [2]*5})
at = pyarrow.Table.from_pandas(df)
engine.consumeArrowTable("t1", at, fragment_size=2)
cursor = engine.executeDML("SELECT a from t1;")

res = cursor.getArrowTable()
print(res.to_pandas())
print("### FINISHED ###")
```
which I launch via 
```
PYTHONPATH=/nfs/site/home/gnovichk/shm/modin MODIN_OMNISCI_LAUNCH_PARAMETERS="enable-debug-timer=1, data=omnitmp" MODIN_EXPERIMENTAL=true MODIN_STORAGE_FORMAT=omnisci MODIN_ENGINE=native python table_test.py
```
.  The result is the following:
```
./tt.sh
   a
0  4
1  4
2  4
3  4
4  4
### FINISHED ###
./tt.sh: line 2: 516158 Segmentation fault      (core dumped) PYTHONPATH=/nfs/site/home/gnovichk/shm/modin MODIN_OMNISCI_LAUNCH_PARAMETERS="enable-debug-timer=1, data=omnitmp" MODIN_EXPERIMENTAL=true MODIN_STORAGE_FORMAT=omnisci MODIN_ENGINE=native python table_test.py
```
As you see, now we have finalization problem.  But, we can test the performance improvement, which I am going to do tomorrow, Friday.

2021-12-02 23:25 UTC, ienkovich requested changes
I think we have everything required but there are still multiple code-style comments. There are also some old ones. Please clean up the patch, get rid of all temporary/debug code, use clang-format, etc.

2021-12-02 23:25 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +  CompareColumns(std::array<int32_t,6>{i32_null, 0, i32_null, i32_null, 1, 1}, table->column(1), 3);
This isn't correct and is not enough. Arrow format allows uninitialized memory on place of NULLs. And you have to check nulls bitmap. I guess, comparator should check if the reference value is a sentinel value for NULL and check the bitmap.

2021-12-02 23:25 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +  auto i32_null = std::numeric_limits<int32_t>::min();
Use templates from `Shared/InlineNullValues.h`

2021-12-02 23:25 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +  check_file(TABLE6x4_CSV_FILE);
We wanted to integrate the check into `import_file` to avoid manual checks here for each file. Right?

2021-12-02 23:25 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +  std::exit(err);
Please set the error code and use `return` at the end of main instead of `std::exit`.

2021-12-02 23:25 UTC, ienkovich commented on QueryEngine/ArrowResultSetConverter.cpp
> +//  Windows-related headers
Wrong comment, it's `ifndef`.

2021-12-02 23:25 UTC, ienkovich commented on QueryEngine/ArrowResultSetConverter.cpp
> +// ==============================================================
Remove `========`

2021-12-02 23:25 UTC, ienkovich commented on QueryEngine/ArrowResultSetConverter.cpp
> +  CHECK_LT(top_n_,0);
Wrong place for the check. It should be checked in our new converter, this one should support this option.

2021-12-02 23:25 UTC, ienkovich commented on QueryEngine/ArrowResultSetConverter.cpp
> +                                 ? results_->entryCount()
Here `top_n_` check is still missing. Also, please leave a comment why we have this check. Condition then can be simplified.

2021-12-02 23:25 UTC, ienkovich commented on example_3.csv
> +a,b,c
I didn't see usages for this file.

2021-12-02 23:29 UTC, ienkovich commented
> As you see, now we have finalization problem. But, we can test the performance improvement, which I am going to do tomorrow, Friday.
Try to use ASAN for this one. Previously, we had some issues related to a clean-up of arrow data imported from Python.

2021-12-03 14:19 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +  CHECK_LT(top_n_,0);
fixed. resolving.

2021-12-03 14:20 UTC, novichkovg commented on example_3.csv
> +a,b,c
This file has been removed, perhaps not from git. Done. Resolving.

2021-12-03 14:22 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +                                 ? results_->entryCount()
I left this
```
  CHECK_LT(top_n_,0);  // Currently (20211203) there is no support for non-negative top_n_.
```
but I did not simplify the condition as it might be needed in the future (so as to remember about correct way to compute `entry_count`).

2021-12-03 14:24 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +template <typename TYPE, size_t len = 6>
No, it is normal.  I am using this function in other pieces of code with different `len` parameter.  Resolving.

2021-12-03 14:37 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +namespace helpers {
Why?  This will make code more confusing.

2021-12-03 14:45 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  // Loads CSV file, creates Arrow Table from it
This is your code, so I replace it by your commentary.  Resolving.

2021-12-03 15:16 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +namespace helpers {
Anonymous namespaces make all definitions inside static, avoiding name collision with other modules. Here you define functions which are non-local actually and can conflict with other similar definitions in other modules.

2021-12-03 15:16 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +      ("catalog,c",        po::value<std::string>(&catalog_path)->default_value(catalog_path),     "Directory path to OmniSci catalogs")
This usage is extremely confusing, that is why I renamed it.  Should we keep the original naming, although it presents a form of technical debt?

2021-12-03 15:35 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +      ("catalog,c",        po::value<std::string>(&catalog_path)->default_value(catalog_path),     "Directory path to OmniSci catalogs")
Using the same names in all tests, omnisci_server and DBEngine is preferred.

2021-12-03 15:47 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +namespace helpers {
rendered, resolving.

2021-12-03 15:53 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  void create_table (std::string csv_file, std::string table_name, size_t fragment_size) {
Changed to `load_table6x4_csv`. Resolving.

2021-12-03 15:56 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +//  Windows-related headers
changed to `//  OS-specific headers`. Resolving.

2021-12-03 15:59 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  ASSERT_EQ(schema->GetFieldByName("i")->type()->Equals(arrow::int64()), true);
Because first column contains text.

2021-12-03 15:59 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +#include <limits>
Done already. Resolving.

2021-12-03 16:04 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +void CompareColumns(const std::array<TYPE,len> & expected,
changed to `compare_columns`

2021-12-03 16:06 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +//  Testing helper functions for 6x4 table contained in $TABLE6x4_CSV_FILE file.
"returns" did not mean return from a function in this context, it meant "creates". Changed accordingly. resolving.

2021-12-03 16:07 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +void MainChunkedConversionTest(size_t fragment_size) {
changed accordingly. resolving.

2021-12-03 16:22 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +      ("catalog,c",        po::value<std::string>(&catalog_path)->default_value(catalog_path),     "Directory path to OmniSci catalogs")
> Using the same names in all tests, omnisci_server and DBEngine is preferred.
OK, as you say. Change has been rendered, resolving.

2021-12-03 16:28 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +//  Performs tests for 6x4 table contained in $TABLE6x4_CSV_FILE for various values of:
I changed the comment to 
```
//  Performs tests for 6x4 table contained in $TABLE6x4_CSV_FILE for various 
//  values of enable_columnar_output, enable_lazy_fetch, fragment_size
```

> it doesn't run the same test for multiple combinations.

Of course it does, see below (I renamed the function to `test_chunked_conversion`).
```
TEST(DBEngine, ArrowTableChunked_Conversion1) {
  test_chunked_conversion(/*columnar_output=*/false, /*lazy_fetch=*/false, 4);
}

TEST(DBEngine, ArrowTableChunked_Conversion2) {
  test_chunked_conversion(/*columnar_output=*/true, /*lazy_fetch=*/false, 4);
}

TEST(DBEngine, ArrowTableChunked_Conversion3) {
  test_chunked_conversion(/*columnar_output=*/false, /*lazy_fetch=*/true, 4);
}

TEST(DBEngine, ArrowTableChunked_Conversion4) {
  test_chunked_conversion(/*columnar_output=*/true, /*lazy_fetch=*/true, 4);
}
```

2021-12-03 16:29 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +TEST(DBEngine, DataLoading)  {
Changed as requested. Resolving

2021-12-03 16:30 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +//  ========================================================================
removed. resolving.

2021-12-03 16:34 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  check_file(TABLE6x4_CSV_FILE);
`$TABLE6x4_CSV_FILE` is loaded via SQL query, so `import_file()` will not be checking its existence. Besides, I renamed `check_file` into `check_file_existence`.

2021-12-03 16:42 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  std::exit(err);
> Please set the error code and use return at the end of main instead of std::exit.
Why? `std::exit()` works just fine.

2021-12-03 16:43 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +// ==============================================================
Removed. Resolving.

2021-12-03 16:45 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  auto i32_null = std::numeric_limits<int32_t>::min();
which one?  There are several of them, in that file.

2021-12-03 16:46 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  CompareColumns(std::array<int32_t,6>{i32_null, 0, i32_null, i32_null, 1, 1}, table->column(1), 3);
OK, propose your test then.  When we discussed test for NULLs, my proposition sounded fine.

2021-12-03 16:47 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +//  ========================================================================
removed. resolving.

2021-12-03 16:47 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +//  Tests multiplication by 2 of the column with doubles (column "d")
Changed. Resolving.

2021-12-03 16:51 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +//  NOTE: import_file() returns table with Arrow types <dictionary, int64, int64, float64>
If should read 
```
//  NOTE: For $TABLE6x4_CSV_FILE file, import_file() creates table with Arrow
//  types <dictionary, int64, int64, float64> so we perform checks accordingly
```
, so I changed the comment accordingly. Resolving.

2021-12-03 16:53 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +//  Tests getArrowTable() for conditional selection columns (INT "i", DOUBLE "d")
Changed to `//  Two column selection with filtering. The result is empty table.` . Resolving.

2021-12-03 16:54 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  //  + fragment_size -- size of the chunk. If zero (default value) the
Changed to `//  + fragment_size -- fragment size for the table; 0 to use the default value`. Resolving.

2021-12-03 21:08 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  std::exit(err);
Changed to `return err`. Resolving.

2021-12-03 21:16 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +//  Performs tests for 6x4 table contained in $TABLE6x4_CSV_FILE for various values of:
I hope my explanations are clear and correct, resolving for now.

2021-12-03 21:24 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  check_file(TABLE6x4_CSV_FILE);
Added correct handling boost exception presented above.  Resolving.

2021-12-03 21:26 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +// #define VERBOSE  //  Enable if you wish to see the details of execution
Removed. Resolving.

2021-12-03 22:46 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +#define USE_TBB_PARALLEL_FOR
In the current implementation `threading::parallel_for` is broken, it does not compile.  I used it as follows:
```
threading::parallel_for(0, values.size(), [&](size_t idx) { 
      size_t chunk_rows_count = chunks[idx].second;
      int64_t null_count = 0;
      auto res = arrow::AllocateBuffer((chunk_rows_count + 7) / 8);
      CHECK(res.ok());
 ....
  }); // threading::parallel_for
```
as well as 
```
threading::blocked_range<size_t>(0, values.size()), [&](size_t idx) { 
      size_t chunk_rows_count = chunks[idx].second;
      int64_t null_count = 0;
      auto res = arrow::AllocateBuffer((chunk_rows_count + 7) / 8);
      CHECK(res.ok());
 ....
  }); // threading::parallel_for
```
I saved this failed attempt to the branch [novichkovg/arrow-table-conversion-cont-broken-parallel_for](https://github.com/intel-ai/omniscidb/tree/novichkovg/arrow-table-conversion-cont-broken-parallel_for), so that one can inspect what went wrong.

Also, I observe that `threading::parallel_for` is being used only in `./Tests/Shared/ThreadingTest.cpp` and does not seem to appear elsewhere in the code.

@ienkovich , @Garra1980  Please take note of this problem.

2021-12-06 13:07 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +#define USE_TBB_PARALLEL_FOR
It should've been `threading::parallel_for(static_cast<size_t>(0), values.size(), [&](size_t idx) {  ...`. Resolving.  Branch ` novichkovg/arrow-table-conversion-cont-broken-parallel_for ` will be merged to the main branch for this task.

2021-12-06 16:37 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  CompareColumns(std::array<int32_t,6>{i32_null, 0, i32_null, i32_null, 1, 1}, table->column(1), 3);
Changed to correct implementation, resolving.

2021-12-06 16:43 UTC, novichkovg commented on QueryEngine/ResultSet.cpp
> +  return query_mem_desc_.didOutputColumnar()
Done. Resolving.

2021-12-06 18:41 UTC, novichkovg commented
> Changes are required in `modin/experimental/core/execution/native/implementations/omnisci_on_native/partitioning/partition_manager.py` to utilize `getArrowTable` instead of `getArrowRecordBatch`. Changes are simple but we need to remain backward compatible.

It appears that we need to modify `run_exec_plan(cls, plan, index_cols, dtypes, columns)` function (line 214).  In which way should we extend it?  I mean, should we just add another parameter to select between `getArrowTable` and `getArrowRecordBatch` or do smth more sophisticated?

2021-12-06 20:11 UTC, ienkovich commented
> It appears that we need to modify `run_exec_plan(cls, plan, index_cols, dtypes, columns)` function (line 214). In which way should we extend it? I mean, should we just add another parameter to select between `getArrowTable` and `getArrowRecordBatch` or do smth more sophisticated?

This function should use `getArrowTable` when it's available and use `getArrowRecordBatch` otherwise for backward compatibility.

2021-12-06 22:14 UTC, novichkovg commented
> > It appears that we need to modify `run_exec_plan(cls, plan, index_cols, dtypes, columns)` function (line 214). In which way should we extend it? I mean, should we just add another parameter to select between `getArrowTable` and `getArrowRecordBatch` or do smth more sophisticated?
> 
> This function should use `getArrowTable` when it's available and use `getArrowRecordBatch` otherwise for backward compatibility.

replaced
```
         rb = curs.getArrowRecordBatch()
         assert rb is not None
         at = pyarrow.Table.from_batches([rb])
```
by
```
         if hasattr(curs, 'getArrowTable'):
             at = curs.getArrowTable()
         else
             rb = curs.getArrowRecordBatch()
             assert rb is not None
             at = pyarrow.Table.from_batches([rb])
         assert at is not None
```

2021-12-07 13:57 UTC, Garra1980 commented on QueryEngine/CountDistinct.h
> +    lhs[i] = lhs[i] | rhs[i];
this is smth from already merged changes, please don't include in your PR

2021-12-07 14:29 UTC, ienkovich requested changes
I still see some unexpected modifications not related to this PR. Otherwise OK.

2021-12-07 14:29 UTC, ienkovich commented on QueryEngine/ArrowResultSetConverter.cpp
> -    for (auto& field : schema->fields()) {
I don't think this should be removed.

2021-12-07 14:29 UTC, ienkovich commented on QueryEngine/ArrowResultSetConverter.cpp
> +  CHECK_LT(top_n_,
Please, place the comment before the check to avoid a long line causing a multiline check.

2021-12-07 14:29 UTC, ienkovich commented on Tests/CMakeLists.txt
> -add_executable(CodeGeneratorTest CodeGeneratorTest.cpp)
Drop all changes in this file from the PR.

2021-12-07 17:04 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> -    for (auto& field : schema->fields()) {
I did work on `ArrowResultSetConverter::getArrowBatch()`, these are not my changes.  Resolving.

2021-12-07 17:06 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +  CHECK_LT(top_n_,
That was result of `clang-format` workings.  Change to 
```
  // Currently (20211203) there is no support for non-negative top_n_.
  CHECK_LT(top_n_, 0);
```
Resolving.

2021-12-07 17:19 UTC, novichkovg commented on Tests/CMakeLists.txt
> -add_executable(CodeGeneratorTest CodeGeneratorTest.cpp)
Reverted to version of this file from modin branch.  Resolving.

2021-12-07 17:20 UTC, novichkovg commented on Tests/CMakeLists.txt
> +add_executable(CachingFileMgrTest CachingFileMgrTest.cpp)
Dropped. Resolving.

2021-12-07 17:22 UTC, novichkovg commented on QueryEngine/CountDistinct.h
> +    lhs[i] = lhs[i] | rhs[i];
It came from rebase, I think.  Resolving.

2021-12-07 18:00 UTC, ienkovich approved these changes
LGTM!

2021-12-07 18:03 UTC, merged