add plan dump option
intel-ai/omniscidb pull request #223
Opened 2021-12-10 11:43 UTC by Daniel-ND

2021-12-10 11:48 UTC, kurapov-peter requested changes
Please run clang-format, otherwise LGTM

2021-12-10 11:48 UTC, kurapov-peter commented on QueryEngine/RelAlgDagBuilder.cpp
> +  if (! query_plan_output_file.empty()) {
Looks like this is not formatted properly

2021-12-15 10:17 UTC, ienkovich commented on QueryEngine/RelAlgDagBuilder.cpp
> +std::string query_plan_output_file = {""};
All (most of) globals used for options are started with `g_` prefix and defined in `Execute.cpp`. Can we keep it so for more unified code?

2021-12-15 11:10 UTC, Daniel-ND commented on QueryEngine/RelAlgDagBuilder.cpp
> +std::string query_plan_output_file = {""};
fixed

2022-07-21 15:22 UTC, closed without merging