Fix for issue #216
intel-ai/omniscidb pull request #226
Opened 2021-12-15 18:15 UTC by sign60intel

2021-12-22 08:46 UTC, fexolm commented on QueryEngine/ResultSet.cpp
> +      std::vector<int32_t> idx_buff(query_mem_desc_.getEntryCount());
idx_buff seems to be unnecessary, you may use permutation instead.

2021-12-22 08:46 UTC, fexolm commented on QueryEngine/ResultSet.cpp
> +      for (size_t i = 0; i < idx_buff.size(); i++) {
also, not necessary

2021-12-22 08:46 UTC, fexolm commented on QueryEngine/ResultSet.cpp
> +      auto sortkey_val_buff = reinterpret_cast<int64_t*>(new char[buf_size]);
possible memory leak

2021-12-22 08:46 UTC, fexolm commented on QueryEngine/ResultSet.cpp
> +      std::vector<int64_t> tmp_buff(query_mem_desc_.getEntryCount());
it seems to be unused

2021-12-22 08:46 UTC, fexolm commented on QueryEngine/ResultSet.cpp
> +    auto sortkey_val_buff = reinterpret_cast<int64_t*>(new char[buf_size]);
possible memory leak

2021-12-22 08:46 UTC, fexolm commented on QueryEngine/ResultSet.cpp
> +    auto sortkey_val_buff = reinterpret_cast<int64_t*>(new char[buf_size]);
do we really need to change radixSortOnCpu somehow? Why?

2021-12-22 08:46 UTC, fexolm commented on QueryEngine/InPlaceSort.cpp
>    switch (chosen_bytes) {
why do we need to change that function?

2021-12-22 08:46 UTC, fexolm commented on QueryEngine/InPlaceSort.cpp
> +                              int32_t* idx_buff,
also, I don't understand, how we use it

2021-12-22 08:46 UTC, fexolm commented on QueryEngine/InPlaceSort.cpp
> +    thrust::sort_by_key(val_buff, val_buff + entry_count, idx_buff, thrust::greater<T>());
It seems, we couldn't use `greater` comparator, if we want to deal with nulls. We need a custom one

2021-12-22 08:46 UTC, fexolm commented on QueryEngine/InPlaceSort.cpp
> +  thrust::sequence(idx_buff, idx_buff + entry_count);
we won't need it, if we would just use permutation buffer, which is already initialized

2021-12-22 08:46 UTC, fexolm commented on QueryEngine/ResultSet.cpp
> +      const auto chosen_bytes = query_mem_desc_.getPaddedSlotWidthBytes(target_idx);
```suggestion
      const auto slot_width = query_mem_desc_.getPaddedSlotWidthBytes(target_idx);
```

2021-12-22 08:46 UTC, fexolm commented on CMakeLists.txt
> +    add_definitions("-DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_TBB")
It could be a problem if we use both TBB and CUDA

2021-12-22 08:55 UTC, fexolm commented on QueryEngine/InPlaceSort.cpp
> +    thrust::sort_by_key(val_buff, val_buff + entry_count, idx_buff, thrust::greater<T>());
also, we could handle it on permutation initialization by moving all null's indices to the begin/end of the permutation

2021-12-24 09:40 UTC, fexolm commented on QueryEngine/ResultSet.cpp
> +  thrust::sequence(idx_buff, idx_buff + entry_count);
we don't need that call, as permutation should be already initialize at this time

2022-01-11 09:01 UTC, fexolm requested changes

2022-01-11 09:01 UTC, fexolm commented on QueryEngine/ResultSetIteration.cpp
> +      setCurVal(value);
This looks like a hack, let's try to find better way to get buffer ith value

2022-01-12 14:38 UTC, fexolm approved these changes
LGTM now

2022-01-13 13:26 UTC, ienkovich requested changes
The patch looks good! There are several minor comments though.

2022-01-13 13:26 UTC, ienkovich commented on QueryEngine/ResultSet.cpp
> +        std::vector<int8_t> sortkey_val_buff(buf_size);
Please use `std::unique_ptr<int8_t[]> sortkey_val_buff(new int8_t[buf_size]);` to avoid buffer zeroing on allocation.

2022-01-13 13:26 UTC, ienkovich commented on QueryEngine/ResultSet.cpp
> +        break;
No `break` is needed here and in the next `default`.

2022-01-13 13:26 UTC, ienkovich commented on QueryEngine/ResultSet.cpp
> +    CHECK(false);
BTW, you can also use something like `UNREACHABLE() << "Unsupported element type";` (not a requirement).

2022-01-13 13:26 UTC, ienkovich commented on QueryEngine/ResultSet.cpp
> +    for (; end >= begin;) {
`while (end > begin)` here and below?

2022-01-13 13:26 UTC, ienkovich commented on QueryEngine/ResultSet.cpp
> +inline V get_null_value() {
It looks like there are multiple places where we want to have such a trait. Probably, rename it to `inline_null_value` and move to `Shared/InlineNullValues.h`?

2022-01-13 19:55 UTC, ienkovich approved these changes
LGTM!

2022-01-13 20:19 UTC, merged