Novichkovg/issue245 performance degradation
intel-ai/omniscidb pull request #255
Opened 2022-01-18 21:05 UTC by novichkovg

Performance degradation is fixed now, via `threading::parallel_for`.

2022-01-19 13:29 UTC, ienkovich requested changes

2022-01-19 13:29 UTC, ienkovich commented on QueryEngine/ArrowResultSetConverter.cpp
> +    const size_t stride = (entry_count + cpu_count - 1) / cpu_count;
Such stride and threads/tasks count computation was ok for `std::async` but is not really good for TBB. I think we should have minimal stride (like 64KB block or something like that), max stride (like several MB block), and result set implied (like entry / (cpu_count * 4) which should be adjusted using min and max values. After stride computation, we can determine the number of tasks and allocated vectors accordingly. We can discuss it if you have other ideas.

2022-01-19 13:29 UTC, ienkovich commented on QueryEngine/ArrowResultSetConverter.cpp
> +      auto timer = DEBUG_TIMER("append rows to arrow, multiple threads");
There are no multiple threads here. Guess, we need to use parallel_for and process each column in parallel.

2022-01-19 13:29 UTC, ienkovich commented on QueryEngine/ArrowResultSetConverter.cpp
> +        if (!columnar_conversion_flags.empty() && columnar_conversion_flags[i]) {
The emptiness check was copied from the record batch conversion, but here it's not needed (you have multiple accesses to this vector without emptiness check anyway).

2022-01-19 13:29 UTC, ienkovich commented on QueryEngine/ArrowResultSetConverter.cpp
> +            continue;
Probably put `append` under if instead to avoid nested `continue` and have simpler code?

2022-01-19 13:29 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +  test_single_column_table<int8_t>(30'000'000, 150);
Is it really important to have so many rows? The important thing here is to have multiple columns and fragments.

2022-01-19 16:24 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  test_single_column_table<int8_t>(30'000'000, 150);
Why not to have so many?  The software is intended with big data so why not to check it in the like environment?

2022-01-19 16:26 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +        if (!columnar_conversion_flags.empty() && columnar_conversion_flags[i]) {
removed, resolving.

2022-01-19 16:35 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +      auto timer = DEBUG_TIMER("append rows to arrow, multiple threads");
Maybe not, it depends on how long it take the loop to run.

2022-01-19 16:35 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +            continue;
I reworked the code keeping the same logic.

2022-01-19 16:55 UTC, ienkovich commented on Embedded/EmbeddedDbTest.cpp
> +  test_single_column_table<int8_t>(30'000'000, 150);
Using big input for tests makes sense in performance testing. For UT it doesn't improve coverage but increases the testing time. If 1 000 000 or 1 000 rows test has the same coverage then there is no reason to spend additional CPU and memory for it.

2022-01-19 16:59 UTC, ienkovich commented on QueryEngine/ArrowResultSetConverter.cpp
> +      auto timer = DEBUG_TIMER("append rows to arrow, multiple threads");
`append` is O(buffer_size), so there is a reason to parallelize.

2022-01-19 16:59 UTC, ienkovich commented on QueryEngine/ArrowResultSetConverter.cpp
> +            continue;
The updated version looks good. Thanks!

2022-01-19 18:05 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +    const size_t stride = (entry_count + cpu_count - 1) / cpu_count;
I change stride segment count to the following:
```    
    const size_t effective_entry_sizeof = 4; // needs to be computed
    const size_t stride = std::clamp (entry_count, 65536/effective_entry_sizeof, 8*1048576/effective_entry_sizeof);
    const size_t segments_count = (entry_count + stride - 1)/stride;
```

However, as a result of this change I observe 2x performance degradation:
```
  ================ ================ =========== ===========
  --                                     ascending_list
  --------------------------------- -----------------------
       shape        columns_number     False        True
  ================ ================ =========== ===========
   [10000000, 10]         1          11.6▒0.5s   11.4▒0.2s
   [10000000, 10]         5          16.9▒0.7s   18.5▒0.7s
  ================ ================ =========== ===========
  started: 2022-01-19 20:55:24, duration: 8.90m
```
Originally values looked like this:
```
  ================ ================ =========== ===========
  --                                     ascending_list
  --------------------------------- -----------------------
       shape        columns_number     False        True
  ================ ================ =========== ===========
   [10000000, 10]         1          3.07▒0.1s   3.01▒0.1s
   [10000000, 10]         5          9.59▒0.6s   10.8▒0.6s
  ================ ================ =========== ===========
  started: 2022-01-18 23:40:31, duration: 4.50m
```

2022-01-19 18:30 UTC, ienkovich commented on QueryEngine/ArrowResultSetConverter.cpp
> +    const size_t stride = (entry_count + cpu_count - 1) / cpu_count;
My proposal was to use `entry_count / cpu_count() / 2 (or 4)` for `clamp`, not simply `entry_count`.

2022-01-19 21:30 UTC, novichkovg commented on Embedded/EmbeddedDbTest.cpp
> +  test_single_column_table<int8_t>(30'000'000, 150);
Change to  `1 000 000` now it runs like this:
```
[ RUN      ] DBEngine.LargeTables
[       OK ] DBEngine.LargeTables (818 ms)
[ RUN      ] DBEngine.LargeTablesRowWise
[       OK ] DBEngine.LargeTablesRowWise (915 ms)
```
Fast enough?

2022-01-20 14:10 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +      auto timer = DEBUG_TIMER("append rows to arrow, multiple threads");
Changed to the following:
```
      threading::parallel_for(static_cast<int>(0), schema->num_fields(), [&](int i) {
        if (!columnar_conversion_flags[i]) {
          for (size_t j = 0; j < segments_count; ++j) {
            if (column_value_segs[j][i]) {
              append(builders[i], *column_value_segs[j][i], null_bitmap_segs[j][i]);
            }
          }
        }
      });
```
Obtained result looks as follows:
```
  ================ ================ ============ ===========
  --                                     ascending_list
  --------------------------------- ------------------------
       shape        columns_number     False         True
  ================ ================ ============ ===========
   [10000000, 10]         1          1.98▒0.04s   1.92▒0.1s
   [10000000, 10]         5          8.35▒0.5s    9.89▒0.7s
  ================ ================ ============ ===========
  started: 2022-01-20 16:56:56, duration: 4.04m
```
, whereas performance of the version where that loop is not parallelized looks like
```
  ================ ================ ============ ===========
  --                                     ascending_list
  --------------------------------- ------------------------
       shape        columns_number     False         True
  ================ ================ ============ ===========
   [10000000, 10]         1          3.13▒0.01s   3.11▒0.1s
   [10000000, 10]         5          9.51▒0.7s    10.6▒0.7s
  ================ ================ ============ ===========
  started: 2022-01-20 00:34:39, duration: 4.53m
```
It appears that this parallelization improved overall performance by 17%.

2022-01-20 16:56 UTC, ienkovich commented on QueryEngine/ArrowResultSetConverter.cpp
> +    const size_t effective_entry_sizeof = 4;
Let's put a real size computation instead of this placeholder. E.g.
```
size_t effective_entry_sizeof = 0;
for (size_t i = 0; i < col_count; ++i) {
  effective_entry_sizeof += results_->getColType(i).get_size();
}
CHECK_GT(effective_entry_sizeof, 0);
```

2022-01-20 16:58 UTC, ienkovich commented on QueryEngine/ArrowResultSetConverter.cpp
> +            row_count += convert_rowwise(results_,
This would count `row_count * col_count`.

2022-01-20 18:29 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +    const size_t effective_entry_sizeof = 4;
I was thinking about computing average value of the sizeofs of columns; other options could median or maximum sizeof.

In this proposed version one can have very large `effective_entry_sizeof` for, say, 1000s of columns.

Please let me know your thoughts.

2022-01-20 18:43 UTC, ienkovich commented on QueryEngine/ArrowResultSetConverter.cpp
> +    const size_t effective_entry_sizeof = 4;
What's the problem with big row sizes? Row size affects the min and max number of rows in a single TBB task, it's OK to have fewer rows in a task if the row size is very big.

2022-01-20 19:31 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +    const size_t effective_entry_sizeof = 4;
OK, what is the meaning of the computation you propose?  In my (original) version with `const size_t effective_entry_sizeof = 4`  the `effective_entry_sizeof` parameter is used to translate 64K (8MB) into the number of entries between which the  spread is  clamped.  I used `4` only for the time being.

2022-01-20 19:50 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +    const size_t effective_entry_sizeof = 4;
What one can do is to find the most frequent `sizeof(TYPE)` among columns and use that as `effective_entry_sizeof`. The code would something like this
```
std::unordered_set<size_t> sizeofs;
for (size_t i = 0; i < col_count; ++i) {
  sizeofs[results_->getColType(i).get_size()]++;
}

auto  max_elem_iter = std::max_element(std::begin(sizeofs), std::end(sizeofs), 
[](const std::pair<whatever> & p1, const std::pair<whatever> & p2) { return p1.second<p2.second;});
effective_entry_sizeof = max_elem_iter->first;
```

2022-01-20 20:24 UTC, ienkovich commented on QueryEngine/ArrowResultSetConverter.cpp
> +    const size_t effective_entry_sizeof = 4;
I don't see why you care about the average or most frequent column size. We want to split the table into chunks and keep them between 64KB and 8MB, to translate these border values into row count we use effective_entry_sizeof which should be equal to row size.

2022-01-20 20:28 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +    const size_t effective_entry_sizeof = 4;
Ah, if so it makes sense.  Probably need to `ceil` the result.

2022-01-20 21:31 UTC, novichkovg commented on QueryEngine/ArrowResultSetConverter.cpp
> +    const size_t effective_entry_sizeof = 4;
Changed as requested.  There results are:
```  ================ ============ ============ =========== ===========
  --                        columns_number / ascending_list
  ---------------- -------------------------------------------------
       shape        1 / False     1 / True    5 / False    5 / True
  ================ ============ ============ =========== ===========
   [10000000, 10]   1.91▒0.05s   2.01▒0.02s   8.32▒0.7s   9.66▒0.7s
  ================ ============ ============ =========== ===========
  started: 2022-01-21 00:26:24, duration: 3.98m
```
So it seems we gained further improvement.  Changes are pushed.

2022-01-21 09:35 UTC, ienkovich approved these changes
LGTM!

2022-01-21 09:36 UTC, merged