[WIP] Separate kernel compilation from execution
intel-ai/omniscidb pull request #271
Opened 2022-01-31 15:34 UTC by fexolm

fixes #249

2022-02-16 00:39 UTC, alexbaden commented
Am I understanding correctly that what has been done here is to take the fragment indices endpoint and essentially expose it outside the executor, so you can make successive calls to execute with more and more fragments?

I would be curious in a performance comparison between this and calling `executeWorkUnitPerFragment` with the same query. What are the overheads we are trying to resolve by adding these new endpoints?

2022-02-16 13:47 UTC, kurapov-peter reviewed
Merging seems a bit off?

2022-02-16 13:47 UTC, kurapov-peter commented on QueryEngine/Execute.cpp
> +                                                  ExecutorDeviceType::CPU,
Is device type going to come from ```StreamExectuionContext```?

2022-02-16 13:47 UTC, kurapov-peter commented on QueryEngine/Execute.h
> +#include "Catalog/Catalog.h"
probably merge artifact?

2022-02-16 15:08 UTC, fexolm commented
Hey, Alex! Thanks for your comment. It seems, that executeWorkUnitPerFragment compiling kernel for each fragments batch. What we are trying to achieve is to do compilation once, and then use that kernel multiple times. I expect executeWorkUnitPerFragment to be much slower, due to the compilation overhead. 

Mostly, I just extracted compilation, execution and reduction stages from executeWorkUnit function to 3 separate functions. I assume, that for now the perfomance should be comparable to executeWorkUnit function, if we would run all kernels in parallel, but I might be wrong. 

I think, the performance of kernel launching is not a priority for now, but that's a good point and I think, I would measure it sometime.

Anyway, do you have some other ideas in mind, how we could implement streaming interface, or this one is good enough?

2022-02-16 15:11 UTC, fexolm commented
Hey @kurapov-peter! It seems, that it is really merge issue. Somehow @sign60intel commits appeared in my branch.

2022-02-16 15:21 UTC, fexolm commented on QueryEngine/Execute.cpp
> +                                                  ExecutorDeviceType::CPU,
Well, it could. I'm not yet sure about keeping that context, it seemed reasonable for me, as I don't want to store additional context in executor. I think, we need to implement some more sophisticated queries support to decide whether we need that context or not.

2022-02-16 15:53 UTC, alexbaden commented
The compiled code is cached though, so it's the overhead of building up the LLVM IR for the work unit and then fetching the bytecode from the cache. I don't think that would be too high, but it would be interesting to know for sure (or if the cache isn't working).

2022-02-21 18:09 UTC, ienkovich requested changes

2022-02-21 18:09 UTC, ienkovich commented on Tests/NoCatalogSqlTest.cpp
> +  (void)ra_executor.runOnBatch({TEST_STREAMING_TABLE_ID, {0, 1}});
Check returned value is correct instead of casting it to void.

2022-02-22 08:42 UTC, fexolm commented on QueryEngine/CompilationOptions.h
> +  std::vector<size_t> outer_fragment_indices{};
To make it copyable

2022-02-22 08:45 UTC, fexolm commented on QueryEngine/Execute.cpp
> +  return ctx->shared_context->getFragmentResults().back().first;
It is used in projection queries, it is going to be changed soon, but it works ok, just for now.

2022-02-22 08:52 UTC, fexolm commented on QueryEngine/Execute.cpp
> +  auto kernel = std::make_unique<ExecutionKernel>(ctx->ra_exe_unit,
We need to discuss if runOnBatch should support multiple batches in a single call.

2022-02-22 08:53 UTC, fexolm commented on QueryEngine/ExecutionKernel.cpp
> +        all_tables_fragments[qi.table_id] = &streaming_table_fragments.back();
Yeah, good point

2022-02-22 08:54 UTC, fexolm commented on QueryEngine/ExecutionKernel.cpp
> +        all_tables_fragments[qi.table_id] = &streaming_table_fragments.back();
Anyway, this is also going to be changed some time, as it is dirty hack :D

2022-02-22 08:56 UTC, fexolm commented on QueryEngine/RelAlgExecutor.cpp
> +  auto lock = acquire_execute_mutex(executor_);
IDK, just a copy paste :D

2022-02-22 08:58 UTC, fexolm commented on QueryEngine/RelAlgExecutor.cpp
> +  // so it should do cleanup session info after finishing its execution
It should be uncommented at some time, as we still need to do executor cleanup. I've created an issue for that.

2022-02-22 09:06 UTC, fexolm commented on Tests/NoCatalogRelAlgTest.cpp
> +TEST_F(NoCatalogRelAlgTest, StreamingAggregate) {
For some reason, I have an issue with calcite server locally, so I couldn't run SQL tests, I will remove RA tests as soon as I fix this.

2022-02-22 09:08 UTC, fexolm commented on Tests/NoCatalogSqlTest.cpp
> +  (void)ra_executor.runOnBatch({TEST_STREAMING_TABLE_ID, {0, 1}});
I will, as soon as returned value for aggregations will be stabilized.

2022-02-22 09:12 UTC, fexolm commented on QueryEngine/Execute.cpp
> +  ctx->co = co;
Not sure I understand what you mean

2022-02-22 09:13 UTC, fexolm commented on QueryEngine/Execute.cpp
> +      if (ctx->ra_exe_unit.estimator) {
I don't really understand all that estimators staff yet, lets discuss it later.

2022-02-22 09:29 UTC, fexolm commented on QueryEngine/Execute.cpp
> -      const auto fragments_it = all_tables_fragments.find(table_id);
Yeah, it looks unnecessary anymore

2022-02-22 11:34 UTC, fexolm commented on QueryEngine/CompilationOptions.h
> +  std::vector<size_t> outer_fragment_indices{};
To enable assign operator

2022-02-25 12:34 UTC, ienkovich requested changes

2022-02-25 12:34 UTC, ienkovich commented on QueryEngine/Execute.cpp
> +    auto metadata = data_mgr_->getTableMetadata(db_id_, fragments[0].table_id);
Please, add some check for `fragments` size.

2022-03-01 12:24 UTC, merged