WIP Fix i310 Removed a single DB ID restrictions
intel-ai/omniscidb pull request #311
Opened 2022-02-28 14:42 UTC by sign60intel

2022-03-01 11:53 UTC, fexolm commented
Could you please rebase this pr to appropriate branch, so we can see only relevant changes?

2022-03-28 21:42 UTC, ienkovich requested changes

2022-03-28 21:42 UTC, ienkovich commented on ArrowStorage/ArrowStorage.cpp
>  const DictDescriptor* ArrowStorage::getDictMetadata(int db_id,
Don't add an additional method to get a dictionary, modify the existing one instead.

2022-03-28 21:42 UTC, ienkovich commented on ArrowStorage/ArrowStorage.cpp
> +  CHECK_EQ(dict_id, (dict_id & 0xffffff));
I don't get this check. `dict_id` is supposed to have `schema_id` in its highest byte. It doesn't have to be 0, it has to match the one stored in `db_id_`.

2022-03-28 21:42 UTC, ienkovich commented on ArrowStorage/ArrowStorage.cpp
> +  int _dict_id = dict_id & 0xffffff;
You should use full id here, but change the place where ID is assigned to dictionaries to include schema ID into it. See `ArrowStorage::createTable`

2022-03-28 21:42 UTC, ienkovich commented on ArrowStorage/ArrowStorage.h
> +  ArrowStorage(const std::string& schema_name, int dict_id)
I don't get why you might need this constructor. It makes no sense.

2022-03-28 21:42 UTC, ienkovich commented on DataMgr/DataMgr.cpp
> +  return getPersistentStorageMgr()->getDictMetadata(
This part looks wrong. You should simply pass both parameters to the persistent storage manager.

2022-03-28 21:42 UTC, ienkovich commented on DataMgr/PersistentStorageMgr/PersistentStorageMgr.cpp
> +  return getStorageMgr(schema_id)->getDictMetadata(
`getStorageMgr` makes the shift by itself, so you should simply pass `dict_id`.

2022-03-28 21:42 UTC, ienkovich commented on DataMgr/PersistentStorageMgr/PersistentStorageMgr.cpp
> +      schema_id, dict_id & 0xffffff, load_dict);
Simply forward both parameters.

2022-03-28 21:42 UTC, ienkovich commented on QueryEngine/Execute.h
> -  static const int32_t ERR_GEOS{16};
Please don't mix in GEO stuff into the same PR. This should go into a separate one.

2022-03-28 21:42 UTC, ienkovich commented on Tests/ArrowBasedExecuteTest.cpp
> -  static constexpr int TEST_DB_ID = (TEST_SCHEMA_ID << 24) + 1;
This file should not be modified for your patch, if you have to modify something here, then your patch is most probably wrong. Please remove all modifications from these tests.

2022-03-28 21:42 UTC, ienkovich commented on Tests/ArrowStorageSqlTest.cpp
> -constexpr int TEST_DB_ID = (TEST_SCHEMA_ID << 24) + 1;
These tests shouldn't have any modifications as well.

2022-03-28 21:42 UTC, ienkovich commented on Tests/ArrowStorageTest.cpp
> -constexpr int TEST_DB_ID = (TEST_SCHEMA_ID << 24) + 1;
All changes in this file are also unnecessary.

2022-03-28 21:42 UTC, ienkovich commented on Tests/NoCatalogRelAlgTest.cpp
> -constexpr int TEST_DB_ID = (TEST_SCHEMA_ID << 24) + 1;
Same here

2022-03-28 21:42 UTC, ienkovich commented on Tests/NoCatalogSqlTest.cpp
> -constexpr int TEST_DB_ID = (TEST_SCHEMA_ID << 24) + 1;
And here.

2022-05-20 06:18 UTC, closed without merging