Novichkovg/jit engine use hash table desc
intel-ai/omniscidb pull request #317
Opened 2022-03-09 17:12 UTC by novichkovg

2022-03-10 11:13 UTC, fexolm requested changes

2022-03-10 11:13 UTC, fexolm commented on QueryEngine/GroupByAndAggregate.cpp
> +#include "HashTableDesc.h"
Where do we use it here?

2022-03-10 11:13 UTC, fexolm commented on QueryEngine/HashTableDesc.h
> +inline __attribute__((always_inline))
this attribute is unnecessary

2022-03-10 11:13 UTC, fexolm commented on QueryEngine/NativeCodegen.cpp
> +// #ifndef WITH_JIT_DEBUG
please remove commented code

2022-03-10 11:13 UTC, fexolm commented on QueryEngine/QueryMemoryInitializer.cpp
> +    bool use_hash_table_desc)
can we get this from compilation options?

2022-03-10 11:13 UTC, fexolm commented on QueryEngine/QueryMemoryInitializer.cpp
> +    std::cout << "#### " << __PRETTY_FUNCTION__ << ", desc->size: "  << desc->size << std::endl;
remove debug prints

2022-03-10 11:13 UTC, fexolm commented on QueryEngine/QueryMemoryInitializer.cpp
> +      auto* desc = new HashTableDesc(reinterpret_cast<int8_t*>(group_by_buffer),
well, maybe it's ok, but looks a bit confusingly

2022-03-10 11:13 UTC, fexolm commented on QueryEngine/QueryMemoryInitializer.h
> +  // const std::vector <int64_t*> getGroupByHashTableDescPtr() {
remove commented code

2022-03-10 11:13 UTC, fexolm commented on QueryEngine/QueryMemoryInitializer.h
> +  // std::vector<HashTableDesc*> group_by_hash_table_descs_;
commented code

2022-03-10 11:13 UTC, fexolm commented on QueryEngine/ResultSetStorage.cpp
> +    , hash_table_desc_{buff, query_mem_desc.getEntryCount()}
do we use it somewhere?

2022-03-10 11:13 UTC, fexolm commented on ThriftHandler/CommandLineOptions.h
> +extern bool g_use_groupby_buffer_desc;
it seems like this option is declared in 2 files.

2022-03-10 11:52 UTC, novichkovg commented on QueryEngine/NativeCodegen.cpp
> +// #ifndef WITH_JIT_DEBUG
The code is needed, reverted to the uncommented state.  Resolving.

2022-03-10 11:53 UTC, novichkovg commented on QueryEngine/GroupByAndAggregate.cpp
> +#include "HashTableDesc.h"
Removed.  Resolving.

2022-03-10 11:53 UTC, novichkovg commented on QueryEngine/CMakeLists.txt
> +#    GeoIR.cpp
Removed. Resolving.

2022-03-10 11:57 UTC, novichkovg commented on QueryEngine/QueryMemoryInitializer.cpp
> +    std::cout << "#### " << __PRETTY_FUNCTION__ << ", desc->size: "  << desc->size << std::endl;
removed. Resolving.

2022-03-10 11:57 UTC, novichkovg commented on QueryEngine/QueryMemoryInitializer.h
> +  // const std::vector <int64_t*> getGroupByHashTableDescPtr() {
removed. Resolving.

2022-03-10 11:58 UTC, novichkovg commented on QueryEngine/QueryMemoryInitializer.h
> +  // std::vector<HashTableDesc*> group_by_hash_table_descs_;
removed. Resolving.

2022-03-10 13:49 UTC, novichkovg commented on QueryEngine/HashTableDesc.h
> +inline __attribute__((always_inline))
Yes, it is necessary.  `inline` keyword, used solely, acts as a **suggestion** for the compiler to inline.  To force inlining one has to use `__attribute__((always_inline))` attribute.

https://stackoverflow.com/questions/7108797/can-i-selectively-force-inline-a-function

2022-03-10 14:54 UTC, novichkovg commented on QueryEngine/HashTableDesc.h
> +inline __attribute__((always_inline))
Changed to inside class definition. Resolving.

2022-03-10 15:09 UTC, novichkovg commented on QueryEngine/QueryMemoryInitializer.cpp
> +    bool use_hash_table_desc)
`CompilationOptions` has this parameter (`use_groupby_buffer_desc`), but why should `QueryMemoryInitializer`'s ctor know about `CompilationOptions` class?  One can invoke constructor as `CompilationOptions(..., co.use_hash_table_desc)`.  

The proposed change increases the complexity and is undesirable.

2022-03-10 16:07 UTC, novichkovg commented on QueryEngine/ResultSetStorage.cpp
> +    , hash_table_desc_{buff, query_mem_desc.getEntryCount()}
@ienkovich RFC, please let us know your thoughts.

2022-03-10 20:29 UTC, ienkovich requested changes
Overall patch looks OK. But there are two descriptors allocated in different places and some unrelated changes in the PR.

2022-03-10 20:29 UTC, ienkovich commented on QueryEngine/Execute.cpp
> +  query_mem_desc.setEntryCount(10000);  // TODO(fexolm) set appropriate entry count
This line makes the code above useless. Why is it here and how is it related to hash table descriptor?

2022-03-10 20:29 UTC, ienkovich commented on QueryEngine/Execute.cpp
> +ResultSetPtr Executor::doStreamingReduction(std::shared_ptr<StreamExecutionContext> ctx) {
I don't like all these new namings. Why are they in this patch?

2022-03-10 20:29 UTC, ienkovich commented on QueryEngine/Globals.cpp
> +// Globals
The file header is missing. `Globals` comment is already in the file name.

2022-03-10 20:29 UTC, ienkovich commented on QueryEngine/Globals.h
> +extern bool g_use_groupby_buffer_desc;
The header and new line at the end of the file are missing.

2022-03-10 20:29 UTC, ienkovich commented on QueryEngine/NativeCodegen.cpp
> -  if (query_mem_desc->getQueryDescriptionType() ==
Why is this removed?

2022-03-10 20:29 UTC, ienkovich commented on QueryEngine/ResultSetStorage.cpp
> +    , hash_table_desc_{buff, query_mem_desc.getEntryCount()}
It's quite confusing that you add a descriptor here and allocate another one in `QueryMemoryInitializer`. We definitely don't need both.

2022-03-11 19:03 UTC, novichkovg commented on QueryEngine/CMakeLists.txt
> +    Globals.cpp
As discussed with @ienkovich , Globals.cpp were move to `Shared" and serve as a start of the effort to move all global variables to Globals.cpp.

Resolving.

2022-03-11 19:06 UTC, novichkovg commented on QueryEngine/Globals.cpp
> +// Globals
Added header, removed `Globals` comment.  Resolving.

2022-03-11 19:07 UTC, novichkovg commented on QueryEngine/Globals.h
> +extern bool g_use_groupby_buffer_desc;
Added header, and  new line at the end of the file.  Resolving.

2022-03-11 19:10 UTC, novichkovg commented on QueryEngine/QueryMemoryInitializer.cpp
> +      auto* desc = new HashTableDesc(reinterpret_cast<int8_t*>(group_by_buffer),
As discussed, this solution (with appropriate `reinterpret_cast` where necessary) provides code with fewest LOC possible.  And it works.

Resolving.

2022-03-11 19:14 UTC, novichkovg commented on QueryEngine/Execute.cpp
> +ResultSetPtr Executor::doStreamingReduction(std::shared_ptr<StreamExecutionContext> ctx) {
We need to ask @fexolm why.  I did not introduce them.

2022-03-11 19:16 UTC, novichkovg commented on QueryEngine/NativeCodegen.cpp
> -  if (query_mem_desc->getQueryDescriptionType() ==
Dunno, not my change.

2022-03-11 19:34 UTC, novichkovg commented on ThriftHandler/CommandLineOptions.h
> +extern bool g_use_groupby_buffer_desc;
Added `#include "Shared/Globals.h"` to `ThriftHandler/CommandLineOptions.cpp` and removed this line.  In the future all globals will be accessed via  including `"Shared/Globals.h"`.

Resolving.

2022-03-11 19:35 UTC, novichkovg commented on QueryEngine/ResultSetStorage.cpp
> +    , hash_table_desc_{buff, query_mem_desc.getEntryCount()}
Removed from `QueryEngine/ResultSetStorage.{h,cpp}`.  Only in `QueryMemoryInitializer` is left.

Resolving.

2022-03-11 22:09 UTC, novichkovg commented on QueryEngine/Execute.cpp
> +ResultSetPtr Executor::doStreamingReduction(std::shared_ptr<StreamExecutionContext> ctx) {
Reverted to `Executor::finishStreamExecutio()`.  Resolving.

2022-03-14 13:14 UTC, novichkovg commented on QueryEngine/Execute.cpp
> +  query_mem_desc.setEntryCount(10000);  // TODO(fexolm) set appropriate entry count
added a temporary (of 10000) and a reminder that the value should be received from the estimator.  Resolving.

2022-03-15 10:24 UTC, fexolm requested changes

2022-03-15 10:24 UTC, fexolm commented on QueryEngine/NativeCodegen.cpp
> -  if (query_mem_desc->getQueryDescriptionType() ==
Please get rid of irrelevant changes from your pr

2022-03-15 10:30 UTC, fexolm commented on QueryEngine/QueryExecutionContext.cpp
> +                                                            g_use_groupby_buffer_desc,
well, we don't want to use a global here.

2022-03-15 10:42 UTC, fexolm commented on QueryEngine/CompilationOptions.h
> +                              in.use_groupby_buffer_desc};
mb use_size_agnostic_codegen?

2022-03-24 03:14 UTC, ienkovich requested changes
I left some comments over the code and there are also several requests:
1. Make sure all new files have a license hearer.
2. Please avoid unrelated changes like new vertical spaces in those functions you don't need to modify for your PR
3. There are a few files with a missing newline at the end
4. New global should only be used in compilation options structure initialization

2022-03-24 03:14 UTC, ienkovich commented on QueryEngine/GroupByAndAggregate.cpp
> +llvm::Value* GroupByAndAggregate::castToHashPtr(llvm::Value* groups_buffer) {
`castToHashPtr` is confusing because this function not simply casts pointer but also loads a buffer pointer from a structure. Probably `genLoadBufferPtrFromHashDesc`?

2022-03-24 03:14 UTC, ienkovich commented on QueryEngine/QueryMemoryInitializer.cpp
> +    group_by_buffers_.push_back(reinterpret_cast<int64_t*>(desc));
Holder creation is missing here.

2022-03-25 04:28 UTC, ienkovich requested changes
I added a bunch of suggestions for unrelated changes removal. Also, window functions look like a weak part of this PR. I don't actually understand whether we use descriptors in this case or not.

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/GroupByAndAggregate.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/GroupByAndAggregate.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/GroupByAndAggregate.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/GroupByAndAggregate.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/GroupByAndAggregate.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/GroupByAndAggregate.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/GroupByAndAggregate.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/GroupByAndAggregate.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/GroupByAndAggregate.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/GroupByAndAggregate.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/GroupByAndAggregate.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/GroupByAndAggregate.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/NativeCodegen.cpp
> +
```suggestion

```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/QueryExecutionContext.cpp
> +                                                            g_use_groupby_buffer_desc,
Agree on that

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/RelAlgExecutor.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/RelAlgExecutor.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/RelAlgExecutor.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/RelAlgExecutor.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/RelAlgExecutor.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/RelAlgExecutor.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryRunner/QueryRunner.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on ThriftHandler/DBHandler.cpp
> +            << std::endl;
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on ThriftHandler/DBHandler.cpp
> +
```suggestion
```

2022-03-25 04:28 UTC, ienkovich commented on QueryEngine/QueryMemoryInitializer.cpp
> +    if (query_mem_desc.getQueryDescriptionType() ==
It's not fully clear to me what we do with window functions. If we do use descriptors for them, then a proper codegen place should be handled. If we don't, then we shouldn't use descriptors here in case of a window function.

2022-03-28 23:04 UTC, ienkovich requested changes

2022-03-28 23:04 UTC, ienkovich commented on Tests/NoCatalogSqlTest.cpp
> +  g_use_groupby_buffer_desc = parse_cli_args(argc, argv);
Why to use such a weird construction? What if you want to add another option like linear output, etc.? Just use the same construction we use everywhere and let boost fill this global for you.

2022-03-28 23:04 UTC, ienkovich commented on ThriftHandler/CommandLineOptions.cpp
> +#include "Shared/Globals.h"
This include doesn't seem to be actually used.

2022-03-30 09:07 UTC, kurapov-peter commented on QueryEngine/ExecutionKernel.h
> +                  const CompilationOptions& co,
Hi! I'd vote against using compilation options for execution kernel initialization or elsewhere in kernel's execution flow _unless you plan to compile it_. Otherwise, all the information about the _function_ that the kernel is associated with is represented by `QueryCompilationDescriptor`.

2022-03-30 16:19 UTC, ienkovich commented on QueryEngine/ExecutionKernel.h
> +                  const CompilationOptions& co,
We didn't notice there is a special structure for that. Looks like it has to get an additional field then.

2022-04-01 17:32 UTC, ienkovich approved these changes

2022-04-01 20:29 UTC, fexolm commented
LGTM

2022-04-01 20:30 UTC, fexolm approved these changes
LGTM

2022-04-01 20:33 UTC, merged