Implement calicte server endpoint to process serialized calcite input
intel-ai/omniscidb pull request #43
Opened 2020-06-18 11:09 UTC by fexolm

For some reason, I can not run modin tests again.
I've test this with scipt below:
```python
import os
os.environ['OMNISCI_SERVER'] = "/localdisk/artemale/git/omniscidb/build/bin/omnisci_server"
os.environ['MODIN_EXPERIMENTAL'] = 'True'
os.environ['MODIN_ENGINE'] = 'ray'
os.environ['MODIN_BACKEND'] = 'omnisci'
import modin.pandas as mpd
a = mpd.DataFrame([[1, 11, 101], [1, 21, 201], [2, 12, 102], [2, 22, 202], [2, 32, 302]], columns=['a', 'b', 'c'])
a['d'] = a['a']
a = a.drop(columns='a')
print(a)
```
Can someone validate if tests works, before merging? @ienkovich @Garra1980 ?

2020-06-18 11:18 UTC, Garra1980 commented
Yeah, df's print seems to be broken at the moment. I think you can do print(df.shape) for now

2020-06-18 11:41 UTC, fexolm commented
@Garra1980 it does work on my old brach, I mean for some reason, I can not run unit tests, they just deadlock somewhere without any messages.

2020-07-29 15:06 UTC, fexolm commented
It looks like it works, but let's wait for the release to be done before merging the changes.

2020-07-29 15:08 UTC, fexolm commented
Also, I would need to do some refactoring since there are still many debugging staff in the code.

2020-09-03 11:05 UTC, ienkovich requested changes

2020-09-03 11:25 UTC, fexolm commented on java/calcite/src/main/java/org/apache/calcite/rel/externalize/MapDRelJson.java
> -        return toRex(relInput, literal);
Because it's a bit modified toRex call. toRex does not support this format of decimals

2020-09-03 11:25 UTC, fexolm commented on java/calcite/src/main/java/org/apache/calcite/rel/externalize/MapDRelJson.java
> +  private SqlOperator toOp(String op) {
Omnisci's calcite format does not store operator as a map, it only stores its name. So, the map is not necessary here, furthermore, we have no data to generate this map.

2020-09-03 11:25 UTC, fexolm commented on java/calcite/src/main/java/org/apache/calcite/rel/externalize/MapDRelJson.java
> +        final SqlOperator operator = toOp(op);
see the comments about toOp

2020-09-03 12:02 UTC, ienkovich commented on java/calcite/src/main/java/org/apache/calcite/rel/externalize/MapDRelJson.java
> -        return toRex(relInput, literal);
You still can make a recursive call for other literals. Can we avoid changes here using casts for literals?
My concern is that we change parser semantics here. Can we break something for OmniSci? What is this parser used for in OmniSci?

2020-09-03 12:02 UTC, ienkovich commented on java/calcite/src/main/java/com/mapd/parser/server/CalciteServerHandler.java
> +    if (sqlText.contains("execute calcite")) {
Here we need to check for prefix, we don't want to trigger on some string literal.

2020-09-03 12:41 UTC, fexolm commented on java/calcite/src/main/java/org/apache/calcite/rel/externalize/MapDRelJson.java
> +  private SqlOperator toOp(String op) {
this map is needed only if operator field in json is a map, for omnisci format it does not. I don't see any reasons for keeping that logic, if the only field in map we need is a class name, which is stored in op parameter.

2020-09-03 19:50 UTC, ienkovich approved these changes

2020-09-04 07:58 UTC, merged