Scripts cleanup
intel-ai/omniscidb pull request #564
Opened 2022-10-24 15:26 UTC by kurapov-peter

Let's remove some old stuff. Please let me know if you think any of these might be of any use.

2022-10-26 14:52 UTC, alexbaden approved these changes

2022-10-26 17:51 UTC, leshikus requested changes
`mapd-deps-centos.sh` and `common-functions.sh` are needed for manylinux build; otherwise it's a great PR

2022-11-03 08:59 UTC, kurapov-peter commented
@leshikus anything else?

2022-11-08 22:08 UTC, leshikus approved these changes
Sorry for delay, LGTM

2022-11-08 22:16 UTC, merged