FSI: Implement arrow dictionary inporting
intel-ai/omniscidb pull request #76
Opened 2020-08-24 10:37 UTC by fexolm

It's just a reference implementation. More optimizations and refactoring will come during the global FSI refactoring.

2020-08-25 12:35 UTC, anton-malakhov requested changes
please add/modify a test

2020-08-27 13:19 UTC, fexolm commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +  tg.run([this, dict, &c, &col, arr_col_chunked_array, &tg, &fragments, k = key, mgr]() {
I hope to refactor all FSI one day, so, I'll do that later.

2020-08-27 13:21 UTC, fexolm commented
> please add/modify a test

We don't have tests for embedded FSI yet, it would take some time to add them. Let's wait with them until I could spend all my time to FSI.

2020-09-09 09:58 UTC, fexolm commented
I'll close this and continue working on it in https://github.com/intel-ai/omniscidb/pull/81

2020-09-09 09:58 UTC, closed without merging