[WIP] FSI refactoring
intel-ai/omniscidb pull request #81
Opened 2020-09-09 09:55 UTC by fexolm

2020-09-15 07:22 UTC, anton-malakhov commented
for future reviews: please don't mix style changes and logic modifications.. it is hard to read all together

2020-09-15 09:45 UTC, anton-malakhov requested changes
lets measure performance

2020-09-15 10:06 UTC, fexolm commented
@anton-malakhov I've measured perf on census benchmark. Performance seems unchanged.

2020-09-15 10:14 UTC, anton-malakhov approved these changes

2020-09-17 13:32 UTC, anton-malakhov approved these changes

2020-10-13 22:58 UTC, ienkovich requested changes
The code looks good overall! I have several suggestions though for small clean-ups.

2020-10-13 22:58 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +    arrowFrag.offset += offset;
I didn't see where you initialize `offset` and `sz` fields with `0`. Probably I missed it, but it would be safer to use explicit default values for these fields in `ArrowFragment` definition.

2020-10-13 22:58 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +std::vector<Frag> calculateFragmentsOffsets(arrow::ChunkedArray& array,
Looks like this method should get a constant reference to `arrow::ChunkedArray`

2020-10-13 22:58 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +    // fsi registerTable runs under SqliteLock which
Unfinished comment?

2020-10-13 22:58 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
>        auto dictDesc = const_cast<DictDescriptor*>(
Are we going to modify dictionaries? Why do we need to get rid of `const`?

2020-10-13 22:58 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +          auto& c = *std::next(cols.begin(), col_idx);
Do we need `cols` to be a list? If yes, then still let's move the list traversal out of the loop. We can use something like
```
start = std::next(cols.begin(), range.begin());
end = std::next(start, range.end() - range.begin());
for (auto i = start; i != end; ++i) {
...
}
```

2020-10-13 22:58 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +          if (c.isSystemCol) {
I'd put this before keys build (but a compiler would most probably do it for you anyway).

2020-10-13 22:58 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +            LOG(ERROR) << "Number of columns read from Arrow (" << table.num_columns()
`LOG(ERROR)` doesn't terminate execution, so you would break somewhere later? Did you mean to use `LOG(FATAL)`? `CHECK` would also work fine.

2020-10-13 22:58 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +          throw std::runtime_error(
Could you please explain what can lead to this error? Is this a malformed input table or some error in our logic? I just wonder why we terminate on some errors and throw an exception on others.

2020-10-13 22:58 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +                             ctype == kTEXT && !c.columnType.is_dict_encoded_string(),
It would be nice to put this value into `is_varlen` var for easier reading.

2020-10-13 22:58 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +      // case Type::DICTIONARY: {
Just remove the code if you don't need it anymore.

2020-10-14 07:27 UTC, fexolm commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +      // case Type::DICTIONARY: {
we don't need it yet :) this should be uncommented when arrow 2.0 will be released.

2020-10-14 07:29 UTC, fexolm commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +          throw std::runtime_error(
For instance, this exception is caused by incorrect arrow table, we don't need to crash the server on it. CHECKS used for cases where we likely have a bug in our code.

2020-10-14 07:32 UTC, fexolm commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +            LOG(ERROR) << "Number of columns read from Arrow (" << table.num_columns()
probably we need to add a `continue` here. This is not a critical error, we can try to import table even if there are more columns in arrow than in omnisci, but it can be a bit unexpected to user, if we would import only fist n columns instead of all columns, so we just warn him here.

2020-10-14 07:34 UTC, fexolm commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +    arrowFrag.offset += offset;
they are initialized in getSizeAndOffset, ok, I'll add defaults.

2020-10-14 07:59 UTC, fexolm commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +          auto& c = *std::next(cols.begin(), col_idx);
We don't but omnisci stores them as a list. 
In your example, we would still need to calculate `auto col_idx = std::distance(start, end);`
Maybe we would better do
```
auto columnIter= cols.begin();
for (auto col_idx = range.begin(); col_idx != range.end(); col_idx++) {
          auto& c = *(columnIter++);
```

2020-10-14 09:19 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +      // case Type::DICTIONARY: {
OK, leave some comments about it then.

2020-10-14 09:22 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +          throw std::runtime_error(
Yeah, throwing an exception on incorrect input is OK. I just thought this particular case might indicate an incorrect `is_varlen` value computed by our code.

2020-10-14 09:28 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +            LOG(ERROR) << "Number of columns read from Arrow (" << table.num_columns()
I looked at it from the arrow table import perspective and then it is a critical error. But incorrect `CREATE TABLE` is more probable. Maybe move this code upper break the loop?

2020-10-14 09:30 UTC, ienkovich commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +          auto& c = *std::next(cols.begin(), col_idx);
Yes, this is a fine option.

2020-10-14 12:09 UTC, fexolm commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +            LOG(ERROR) << "Number of columns read from Arrow (" << table.num_columns()
When we importing arrow table, we create omnisci schema based on that table, so it is impossible, that arrow import would follow that way.

2020-10-14 12:15 UTC, fexolm commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
> +          throw std::runtime_error(
We compute is_varlen as `ctype == kTEXT && !c.columnType.is_dict_encoded_string()`, so it couldn't be computed incorrectly, as there is nothing complicated here. The only issue that may happen is that arrow array wouldn't have a data buffer for varlen array. This way we would throw, as input is unexpected. I don't think we should crash the server on such input.

2020-10-14 13:21 UTC, fexolm commented on DataMgr/ForeignStorage/ArrowForeignStorage.cpp
>        auto dictDesc = const_cast<DictDescriptor*>(
Hmm, it looks it is not needed anymore, thanks.

2020-10-14 13:25 UTC, ienkovich approved these changes

2020-10-14 13:26 UTC, merged