Singeltone interface to DBEngine
intel-ai/omniscidb pull request #88
Opened 2020-09-15 15:20 UTC by igalink

1. Singeltone interface added to DBEngine via unique_ptr.
2. Python dbe interface updated to use DBEngine singelton.
3. QueryRunner updated with new init method which allows you to set the calcite port, create new system catalog.

2020-09-17 09:29 UTC, fexolm approved these changes
Maybe we would better use some struct to keep init params, like DbEngineConfig to allow a compile-time check of incorrect parameter names. But the overall design LGTM.

2020-09-17 09:44 UTC, Garra1980 commented
The problem is we get segfault right after modin test is finished.

2020-09-17 14:00 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +        std::cerr << "WARNING: ignoring unknown DBEngine parameter '" << key << "'"
One we have a good way to handle initialization errors, we can also return an error for unknown parameters.

2020-09-17 14:13 UTC, ienkovich commented on QueryRunner/QueryRunner.cpp
> -      cat, user, ExecutorDeviceType::GPU, "");
Why do we need this change?

2020-09-17 14:17 UTC, ienkovich commented on QueryRunner/QueryRunner.cpp
> +  qr_instance_.reset(new QueryRunner(db_path,
If you need new more parameters, please extend an existing version of `init`. You still can introduce a new version, but it should call the generic one like other `init` versions do.

2020-09-17 14:51 UTC, igalink commented on Embedded/Python/dbe.pyx
> -    cdef DBEngine* c_dbe  #Hold a C++ instance which we're wrapping
why?

2020-09-17 14:55 UTC, igalink commented on Embedded/DBEngine.h
> +  static DBEngine* init(const std::string& path = "", int port = DEFAULT_CALCITE_PORT);
agree

2020-09-17 14:55 UTC, igalink commented on Embedded/Python/dbe.pyx
>      def close(self):
closed property?

2020-09-17 15:16 UTC, ienkovich commented on Embedded/Python/dbe.pyx
> -    cdef DBEngine* c_dbe  #Hold a C++ instance which we're wrapping
Because otherwise, you don't guarantee `DBEngine` outlives `PyDbEngine`. You should provide strong guarantees for objects to not die while they still can be used.

2020-09-17 15:19 UTC, ienkovich commented on Embedded/Python/dbe.pyx
>      def close(self):
Well, I think both `close` and `closed`. We have no way to 'close' the engine and it's our responsibility to guarantee that the engine is valid while `PyDbEngine` exists.

2020-09-18 11:52 UTC, fexolm commented on Embedded/DBEngine.cpp
> +  auto engine = DBEngineImpl::get();
As far as I understand we should restrict calling init twice, so, maybe we would need to throw an exception on the second initialization also.

2020-09-18 12:45 UTC, igalink commented on Embedded/Python/dbe.pyx
>      def close(self):
I think that at least the "close" method is used in the ibis when dbe replaces pymapd

2020-09-18 13:13 UTC, igalink commented on Embedded/DBEngine.h
> +  static DBEngine* init(const std::string& path = "", int port = DEFAULT_CALCITE_PORT);
done

2020-09-18 13:14 UTC, igalink commented on Embedded/Python/dbe.pyx
>      def close(self):
"closed" property removed

2020-09-18 13:14 UTC, igalink commented on Embedded/Python/dbe.pyx
> -    cdef DBEngine* c_dbe  #Hold a C++ instance which we're wrapping
done

2020-09-18 13:14 UTC, igalink commented on Embedded/Python/dbe.pyx
>      def closed(self):
removed

2020-09-18 13:14 UTC, igalink commented on Embedded/DBEngine.cpp
> +      std::cerr << "DBEngine uninitialized" << std::endl;
removed

2020-09-18 13:15 UTC, igalink commented on Embedded/DBEngine.cpp
> +  auto engine = DBEngineImpl::get();
done using mutex

2020-09-21 09:12 UTC, fexolm commented on Embedded/DBEngine.cpp
> +    return !!engine_;
that looks strange, please use engine != nullptr instead

2020-09-21 09:18 UTC, fexolm commented on Embedded/DBEngine.cpp
> +  auto engine = DBEngineImpl::get();
you could use atomics to reduce overheads here, what you really need here is just swap the pointer atomically.

2020-09-22 12:10 UTC, igalink commented on QueryRunner/QueryRunner.cpp
> +  qr_instance_.reset(new QueryRunner(db_path,
I didn't find init method suitable for the passed parameters.

2020-09-22 12:20 UTC, igalink commented on Embedded/DBEngine.cpp
> +        std::cerr << "WARNING: ignoring unknown DBEngine parameter '" << key << "'"
return false added for unknown parameters

2020-09-22 12:21 UTC, igalink commented on Embedded/DBEngine.cpp
> +    return !!engine_;
Done

2020-09-22 12:24 UTC, igalink commented on Embedded/DBEngine.cpp
> +  auto engine = DBEngineImpl::get();
dbe initialization is not atomic and is called once

2020-09-22 13:26 UTC, ienkovich requested changes

2020-09-22 13:26 UTC, ienkovich commented on Tests/EmbeddedDatabaseTest.cpp
> +    return 0;
Here test fails and `0` return value looks weird then.

2020-09-22 13:26 UTC, ienkovich commented on Embedded/Python/dbe.pyx
> +            assert DBEngine.init(self.parameters)
We don't allow double `init` calls in C++ but wanted to allow multiple angines in Python if they use the same set of parameters, right?

2020-09-22 13:26 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +std::vector<ColumnDetails> DBEngine::getTableDetails (const std::string& table_name) {
Spurious change?

2020-09-22 13:26 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +  return true;
Here we should return `false` because in this case `init` call didn't initialize any engine and `DBEngine::get` might return an engine with another set of params.

2020-09-22 13:26 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +bool DBEngine::init(const std::string& path, int port) {
I think we should simply build parameters map and call more generic version of `init` here. This is to keep synchronization and double initialization logic in a single place.

2020-09-22 13:26 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +std::mutex g_mutex;
Let's put it into the class scope.

2020-09-22 13:26 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +      std::cerr << "DBEngine initialization failed" << std::endl;
My comment here still wasn't addressed.

2020-09-22 13:26 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +    std::call_once(once_flag_,
`call_once` doesn't fit here. If the first call fails then we still should be allowed to initialize another engine with other parameters. This method is called from synchronized `DBEngine::init` so all we need here is to atomically write `engine_` using `atomic_store`. We also need to process initialization errors. This version always returns `true` even if something goes wrong. See my comments for `DBEngineImpl` ctor.

2020-09-22 13:26 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +    return engine_;
This read access should be atomic, use `atomic_load`.

2020-09-22 14:31 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +    return engine_! = nullptr;
Here is a compilation error BTW.

2020-09-22 17:49 UTC, fexolm commented on Embedded/DBEngine.cpp
> +  auto engine = DBEngineImpl::get();
I meant, we may put the locking after the engine pointer load, if it would be atomic. But it is wrong, and we would still need to double-check the engine after locking, in case it was null. Anyway it could save some time in implementations like 
```
DBEngine *instance() {
   DBEngine::init();
   return DBEngine::get();
} 
```
But it does not seem to be frequently used, so you could just ignore my comment.

2020-09-22 18:32 UTC, fexolm commented on Embedded/DBEngine.cpp
> +  auto engine = DBEngineImpl::get();
Oh, sorry, I see now. Just ignore this :)

2020-09-30 09:35 UTC, ienkovich commented
Replaced with #99

2020-09-30 09:35 UTC, closed without merging