Added support to get inf value when dividing by zero (float only)
intel-ai/omniscidb pull request #92
Opened 2020-09-18 13:19 UTC by abykovsk

2020-09-18 15:40 UTC, ienkovich commented on QueryEngine/RuntimeFunctions.cpp
> +    if (lhs > 0) {                                               \
Please check the Pandas result for 0/0 and provide the same behavior here. Probably, -INF is not what we need.

2020-09-18 15:45 UTC, ienkovich commented on QueryEngine/ArithmeticIR.cpp
> +  if (g_inf_div_by_zero) {
Here you try to produce NULL for integers using `safe_inf_div`. It is wrong because you can produce -NULL. I propose to add FP type check into this condition so that the new flag affects FP only and integers are controlled by `null_div_by_zero`.

2020-09-22 14:58 UTC, ienkovich requested changes
The patch looks good! There are just a few minor comments to fix.

2020-09-22 14:58 UTC, ienkovich commented on MapDServer.cpp
> +                          "Return infinity on division by zero instead of throwing "
Let's specify it is for FP division only.

2020-09-22 14:58 UTC, ienkovich commented on QueryEngine/RuntimeFunctions.cpp
> +  DEF_SAFE_INF_DIV_NULLABLE(type, null_type, safe_inf_div) \
This is instantiated for int types as well and we now need fp types only. We can directly instantiate required `DEF_SAFE_INF_DIV_NULLABLE` for `float` and `double` only. Also, add appropriate `#undef` to match other functions.

2020-09-22 14:58 UTC, ienkovich commented on Tests/ExecuteTest.cpp
> +    c("SELECT f / (f - f) FROM test;", "SELECT 2e308 FROM test;", dt);
Please add a test for -INF as well.

2020-09-24 11:32 UTC, ienkovich requested changes

2020-09-24 11:32 UTC, ienkovich commented on QueryEngine/RuntimeFunctions.cpp
> +#define DEF_BINARY_NULLABLE_ALL_OPS(type, null_type)       \
Please undo reformatting in this otherwise unmodified block

2020-09-24 13:38 UTC, ienkovich approved these changes
Looks great! Thanks!

2020-09-24 13:39 UTC, merged

2020-09-24 15:10 UTC, Garra1980 commented
@abykovsk Congrats with the first commit here!