Exceptions in dbe - to catch properly #1884
intel-ai/omniscidb pull request #95
Opened 2020-09-24 09:38 UTC by igalink

Propogate c++ Exceptions to Python

2020-09-24 11:46 UTC, ienkovich requested changes

2020-09-24 11:46 UTC, ienkovich commented on Embedded/Python/dbe.pyx
> +            print("DBE init: OS error: {0}".format(err))
Please remove all these prints. We need to forward exceptions to the user code and shouldn't print anything.

2020-09-24 13:09 UTC, igalink commented on Embedded/Python/dbe.pyx
> +            print("DBE init: OS error: {0}".format(err))
Done

2020-09-24 13:35 UTC, ienkovich reviewed
Overall the patch looks good but it misses tests.

2020-09-24 13:35 UTC, ienkovich commented on Embedded/DBEngine.cpp
> +      throw std::runtime_error("System catalog uninitialized");
Can we really get here? I don't see how successfully initialized engine may have no catalog.

2020-09-24 13:35 UTC, ienkovich commented on Embedded/DBEngine.cpp
>    DBEngineImpl* engine = getImpl(this);
Not related to this PR but why do we need this cast?

2020-09-24 13:35 UTC, ienkovich commented on Embedded/Python/dbe.pyx
> +            self.check_closed()
There is an extra tab

2020-09-24 13:43 UTC, igalink commented on Embedded/DBEngine.cpp
> +      throw std::runtime_error("System catalog uninitialized");
this is unlikely, but it's better to check than to have a sigfault in python

2020-09-24 13:44 UTC, igalink commented on Embedded/DBEngine.cpp
>    DBEngineImpl* engine = getImpl(this);
"except+" linkage in the DBEngine.pxd requares copy constructor

2020-09-24 13:46 UTC, igalink commented on Embedded/Python/dbe.pyx
> +            self.check_closed()
Removed

2020-09-24 15:15 UTC, ienkovich commented on Embedded/DBEngine.cpp
>    DBEngineImpl* engine = getImpl(this);
I meant `DBEngineImpl* engine = getImpl(this);`

2020-09-24 15:30 UTC, ienkovich requested changes
The test should be automated and integrated into DBE regression testing.

2020-09-24 15:55 UTC, igalink commented on Embedded/DBEngine.cpp
>    DBEngineImpl* engine = getImpl(this);
to avoid virtual functions

2020-09-24 16:28 UTC, ienkovich commented on Embedded/DBEngine.cpp
>    DBEngineImpl* engine = getImpl(this);
You have a weird structure where implementation inherits from the base class which is not actually an interface (why to inherit then?). This code will break if anyone will try to use `DBEngine` as a base class.

It looks to me you try to apply [pimpl](https://en.cppreference.com/w/cpp/language/pimpl) approach but in a weird way. Again, this is not for this PR but this should be fixed eventually (avoid static casts in the base class).

2020-09-28 10:17 UTC, igalink commented
> The test should be automated and integrated into DBE regression testing.

test_exceptions.py changed to use PyTest

2020-09-28 11:17 UTC, ienkovich commented on Embedded/test/test_exceptions.py
> +            with pytest.raises(RuntimeError) as excinfo:
IIUC engine construction here raises an error. In this case, the following code will not be executed.

2020-09-28 11:17 UTC, ienkovich commented on Embedded/test/test_exceptions.py
> +        def f():
Why do you put 'with' blocks into these nested functions?

2020-09-28 12:55 UTC, igalink commented on Embedded/test/test_exceptions.py
> +        def f():
Removed

2020-09-28 12:55 UTC, igalink commented on Embedded/test/test_exceptions.py
> +            with pytest.raises(RuntimeError) as excinfo:
Fixed

2020-09-28 15:06 UTC, ienkovich approved these changes

2020-09-28 15:22 UTC, merged